#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2010  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

umask 022
export PATH=/usr/sbin:/sbin:/usr/bin:/bin

# Give the variables we get passed by pppd an own namespace
for i in IFNAME IPLOCAL IPREMOTE DNS1 DNS2 MACREMOTE LLLOCAL LLREMOTE; do
	export PPP_${i}=${!i}
	unset ${i}
done

. /lib/network/functions

# Zone equals IFNAME
ZONE=${PPP_IFNAME}

assert isset ZONE
assert zone_exists ${ZONE}

HOOK=$(zone_get_hook ${ZONE})

assert isset HOOK
assert hook_zone_exists ${HOOK}

PROGNAME=$(basename ${0})
assert isset PROGNAME

log DEBUG "${PROGNAME} was called with the following parameters:"
log DEBUG "  $@"

hook_zone_exec ${HOOK} ppp-${PROGNAME} ${ZONE}
