#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /etc/functions

message="Unmounting all other currently mounted file systems..."
umount -a -d -r &>/dev/null
evaluate_retval standard


message="Sending all processes the TERM signal..."
killall5 -15
error_value=${?}

sleep 3

(exit ${error_value})
evaluate_retval standard

message="Sending all processes the KILL signal..."
killall5 -9
error_value=${?}

sleep 3

(exit ${error_value})
evaluate_retval standard


log_success_msg "Restarting system..."
reboot -d -f -i
