#!/bin/sh
# Begin /etc/init.d/haldaemon

### BEGIN INIT INFO
# Provides:            haldaemon
# Required-Start:      messagebus
# Should-Start:        $syslog
# Required-Stop:       messagebus
# Should-Stop:         $syslog
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Hardware abstraction layer daemon.
# Description:         Starts the hardware abstraction layer daemon.
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="HAL Daemon"
BIN_FILE="/usr/sbin/hald"

pidfile=/var/run/hald/pid

chk_stat

case "${1}" in
    start)
        start_daemon -p ${pidfile} "${BIN_FILE}" --use-syslog
        evaluate_retval start
        ;;

    stop)
        killproc -p ${pidfile} "${BIN_FILE}"
        evaluate_retval stop
        ;;

    force-reload)
        reloadproc -force
        evaluate_retval force-reload
        ;;

    restart)
        $0 stop
        $0 start
        ;;

    status)
        statusproc -p ${pidfile}
        ;;

    reload)
        reloadproc
        evaluate_retval reload
        ;;

    try-restart)
        pidofproc "${BIN_FILE}" > /dev/null
        if [ "${?}" -ne "0" ]; then
            MESSAGE="${MESSAGE}: Not Running"
        else
            $0 stop
            $0 start
            exit 0
        fi
        evaluate_retval try-restart
        ;;

    *)
        echo "Usage: ${0} {start|stop|{force-}reload|{try-}restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/haldaemon
