#!/bin/sh
# Begin /etc/init.d/network

### BEGIN INIT INFO
# Provides:            $network
# Required-Start:      $local_fs swap localnet
# Should-Start:        $syslog
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts and configures network interfaces.
# Description:         Starts and configures network interfaces.
# X-LFS-Default-Start: S20
# X-LFS-Default-Stop:  K80
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
	start|stop|reload|restart)
		exec /sbin/network $@
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|reload}"
		exit 1
		;;
esac

# End /etc/init.d/network
