#!/bin/sh
# Begin /etc/init.d/sshd

. /lib/lsb/init-functions

MESSAGE="SSH Server"
BIN_FILE="/usr/sbin/sshd"

chk_stat

case "$1" in
    start)
        start_daemon "${BIN_FILE}"
        evaluate_retval start
        ;;

    stop)
        killproc "${BIN_FILE}"
        evaluate_retval stop
        ;;

    reload)
        killproc "${BIN_FILE}" -HUP
        evaluate_retval reload
        ;;

    restart)
        killproc "$BIN_FILE"
        sleep 1
        start_daemon "${BIN_FILE}"
        evaluate_retval restart
        ;;

    status)
        statusproc "${BIN_FILE}"
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/sshd
