#!/bin/sh
###############################################################################
#                                                                             #
# IPFire - An Open Source Firewall Solution                                   #
# Copyright (C) 2011 IPFire development team                                  #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

# This script always returns 0 to prevent the kernel starting its own stp
# implementation.
# But in case no mstpd is not running, an error message will be logged.

. /lib/network/functions

service_is_active mstpd || \
	log ERROR "mstpd is not running. STP might not work."

exit 0
