#!/bin/bash

for file in /lib/network/functions.*; do
	. ${file}
done

# Reading in network tool configuration
network_config_read

# Create run dir
if ! [ -d "${RUN_DIR}" ]; then
	mkdir ${RUN_DIR}
fi
