usr/bin/awk
usr/bin/gawk
usr/bin/gawk-3.1.6
#usr/bin/igawk
#usr/bin/pgawk
#usr/bin/pgawk-3.1.6
#usr/lib/awk
#usr/lib/awk/grcat
#usr/lib/awk/pwcat
#usr/share/awk
#usr/share/awk/assert.awk
#usr/share/awk/bits2str.awk
#usr/share/awk/cliff_rand.awk
#usr/share/awk/ctime.awk
#usr/share/awk/ftrans.awk
#usr/share/awk/getopt.awk
#usr/share/awk/gettime.awk
#usr/share/awk/group.awk
#usr/share/awk/join.awk
#usr/share/awk/libintl.awk
#usr/share/awk/nextfile.awk
#usr/share/awk/noassign.awk
#usr/share/awk/ord.awk
#usr/share/awk/passwd.awk
#usr/share/awk/readable.awk
#usr/share/awk/rewind.awk
#usr/share/awk/round.awk
#usr/share/awk/strtonum.awk
#usr/share/awk/zerofile.awk
#usr/share/info/gawk.info
#usr/share/info/gawkinet.info
#usr/share/locale/ca/LC_MESSAGES/gawk.mo
#usr/share/locale/da/LC_MESSAGES/gawk.mo
#usr/share/locale/de/LC_MESSAGES/gawk.mo
#usr/share/locale/es/LC_MESSAGES/gawk.mo
#usr/share/locale/fr/LC_MESSAGES/gawk.mo
#usr/share/locale/ga/LC_MESSAGES/gawk.mo
#usr/share/locale/he/LC_MESSAGES/gawk.mo
#usr/share/locale/it/LC_MESSAGES/gawk.mo
#usr/share/locale/ja/LC_MESSAGES/gawk.mo
#usr/share/locale/nl/LC_MESSAGES/gawk.mo
#usr/share/locale/pl/LC_MESSAGES/gawk.mo
#usr/share/locale/pt_BR/LC_MESSAGES/gawk.mo
#usr/share/locale/ro/LC_MESSAGES/gawk.mo
#usr/share/locale/rw/LC_MESSAGES/gawk.mo
#usr/share/locale/sv/LC_MESSAGES/gawk.mo
#usr/share/locale/tr/LC_MESSAGES/gawk.mo
#usr/share/locale/vi/LC_MESSAGES/gawk.mo
#usr/share/locale/zh_CN/LC_MESSAGES/gawk.mo
#usr/share/man/man1/gawk.1
#usr/share/man/man1/igawk.1
#usr/share/man/man1/pgawk.1
