etc/vimrc
#usr/bin/ex
#usr/bin/rview
#usr/bin/rvim
usr/bin/vi
#usr/bin/view
usr/bin/vim
#usr/bin/vimdiff
#usr/bin/vimtutor
#usr/bin/xxd
#usr/share/man/fr/man1/evim.1
#usr/share/man/fr/man1/ex.1
#usr/share/man/fr/man1/rview.1
#usr/share/man/fr/man1/rvim.1
#usr/share/man/fr/man1/view.1
#usr/share/man/fr/man1/vim.1
#usr/share/man/fr/man1/vimdiff.1
#usr/share/man/fr/man1/vimtutor.1
#usr/share/man/fr/man1/xxd.1
#usr/share/man/it/man1/evim.1
#usr/share/man/it/man1/ex.1
#usr/share/man/it/man1/rview.1
#usr/share/man/it/man1/rvim.1
#usr/share/man/it/man1/view.1
#usr/share/man/it/man1/vim.1
#usr/share/man/it/man1/vimdiff.1
#usr/share/man/it/man1/vimtutor.1
#usr/share/man/it/man1/xxd.1
#usr/share/man/man1/evim.1
#usr/share/man/man1/ex.1
#usr/share/man/man1/rview.1
#usr/share/man/man1/rvim.1
#usr/share/man/man1/view.1
#usr/share/man/man1/vim.1
#usr/share/man/man1/vimdiff.1
#usr/share/man/man1/vimtutor.1
#usr/share/man/man1/xxd.1
#usr/share/man/pl/man1/evim.1
#usr/share/man/pl/man1/ex.1
#usr/share/man/pl/man1/rview.1
#usr/share/man/pl/man1/rvim.1
#usr/share/man/pl/man1/view.1
#usr/share/man/pl/man1/vim.1
#usr/share/man/pl/man1/vimdiff.1
#usr/share/man/pl/man1/vimtutor.1
#usr/share/man/pl/man1/xxd.1
#usr/share/man/ru/man1/evim.1
#usr/share/man/ru/man1/ex.1
#usr/share/man/ru/man1/rview.1
#usr/share/man/ru/man1/rvim.1
#usr/share/man/ru/man1/view.1
#usr/share/man/ru/man1/vim.1
#usr/share/man/ru/man1/vimdiff.1
#usr/share/man/ru/man1/vimtutor.1
#usr/share/man/ru/man1/xxd.1
#usr/share/vim
#usr/share/vim/vim71
#usr/share/vim/vim71/autoload
#usr/share/vim/vim71/autoload/README.txt
#usr/share/vim/vim71/autoload/ada.vim
#usr/share/vim/vim71/autoload/adacomplete.vim
#usr/share/vim/vim71/autoload/ccomplete.vim
#usr/share/vim/vim71/autoload/csscomplete.vim
#usr/share/vim/vim71/autoload/decada.vim
#usr/share/vim/vim71/autoload/getscript.vim
#usr/share/vim/vim71/autoload/gnat.vim
#usr/share/vim/vim71/autoload/gzip.vim
#usr/share/vim/vim71/autoload/htmlcomplete.vim
#usr/share/vim/vim71/autoload/javascriptcomplete.vim
#usr/share/vim/vim71/autoload/netrw.vim
#usr/share/vim/vim71/autoload/netrwFileHandlers.vim
#usr/share/vim/vim71/autoload/netrwSettings.vim
#usr/share/vim/vim71/autoload/paste.vim
#usr/share/vim/vim71/autoload/phpcomplete.vim
#usr/share/vim/vim71/autoload/pythoncomplete.vim
#usr/share/vim/vim71/autoload/rubycomplete.vim
#usr/share/vim/vim71/autoload/spellfile.vim
#usr/share/vim/vim71/autoload/sqlcomplete.vim
#usr/share/vim/vim71/autoload/syntaxcomplete.vim
#usr/share/vim/vim71/autoload/tar.vim
#usr/share/vim/vim71/autoload/vimball.vim
#usr/share/vim/vim71/autoload/xml
#usr/share/vim/vim71/autoload/xml/html32.vim
#usr/share/vim/vim71/autoload/xml/html401f.vim
#usr/share/vim/vim71/autoload/xml/html401s.vim
#usr/share/vim/vim71/autoload/xml/html401t.vim
#usr/share/vim/vim71/autoload/xml/html40f.vim
#usr/share/vim/vim71/autoload/xml/html40s.vim
#usr/share/vim/vim71/autoload/xml/html40t.vim
#usr/share/vim/vim71/autoload/xml/xhtml10f.vim
#usr/share/vim/vim71/autoload/xml/xhtml10s.vim
#usr/share/vim/vim71/autoload/xml/xhtml10t.vim
#usr/share/vim/vim71/autoload/xml/xhtml11.vim
#usr/share/vim/vim71/autoload/xml/xsd.vim
#usr/share/vim/vim71/autoload/xml/xsl.vim
#usr/share/vim/vim71/autoload/xmlcomplete.vim
#usr/share/vim/vim71/autoload/zip.vim
#usr/share/vim/vim71/bugreport.vim
#usr/share/vim/vim71/colors
#usr/share/vim/vim71/colors/README.txt
#usr/share/vim/vim71/colors/blue.vim
#usr/share/vim/vim71/colors/darkblue.vim
#usr/share/vim/vim71/colors/default.vim
#usr/share/vim/vim71/colors/delek.vim
#usr/share/vim/vim71/colors/desert.vim
#usr/share/vim/vim71/colors/elflord.vim
#usr/share/vim/vim71/colors/evening.vim
#usr/share/vim/vim71/colors/koehler.vim
#usr/share/vim/vim71/colors/morning.vim
#usr/share/vim/vim71/colors/murphy.vim
#usr/share/vim/vim71/colors/pablo.vim
#usr/share/vim/vim71/colors/peachpuff.vim
#usr/share/vim/vim71/colors/ron.vim
#usr/share/vim/vim71/colors/shine.vim
#usr/share/vim/vim71/colors/slate.vim
#usr/share/vim/vim71/colors/torte.vim
#usr/share/vim/vim71/colors/zellner.vim
#usr/share/vim/vim71/compiler
#usr/share/vim/vim71/compiler/README.txt
#usr/share/vim/vim71/compiler/ant.vim
#usr/share/vim/vim71/compiler/bcc.vim
#usr/share/vim/vim71/compiler/bdf.vim
#usr/share/vim/vim71/compiler/checkstyle.vim
#usr/share/vim/vim71/compiler/cs.vim
#usr/share/vim/vim71/compiler/decada.vim
#usr/share/vim/vim71/compiler/dot.vim
#usr/share/vim/vim71/compiler/eruby.vim
#usr/share/vim/vim71/compiler/fortran_F.vim
#usr/share/vim/vim71/compiler/fortran_cv.vim
#usr/share/vim/vim71/compiler/fortran_elf90.vim
#usr/share/vim/vim71/compiler/fortran_g77.vim
#usr/share/vim/vim71/compiler/fortran_lf95.vim
#usr/share/vim/vim71/compiler/fpc.vim
#usr/share/vim/vim71/compiler/gcc.vim
#usr/share/vim/vim71/compiler/gnat.vim
#usr/share/vim/vim71/compiler/hp_acc.vim
#usr/share/vim/vim71/compiler/icc.vim
#usr/share/vim/vim71/compiler/intel.vim
#usr/share/vim/vim71/compiler/irix5_c.vim
#usr/share/vim/vim71/compiler/irix5_cpp.vim
#usr/share/vim/vim71/compiler/javac.vim
#usr/share/vim/vim71/compiler/jikes.vim
#usr/share/vim/vim71/compiler/mcs.vim
#usr/share/vim/vim71/compiler/mips_c.vim
#usr/share/vim/vim71/compiler/mipspro_c89.vim
#usr/share/vim/vim71/compiler/mipspro_cpp.vim
#usr/share/vim/vim71/compiler/modelsim_vcom.vim
#usr/share/vim/vim71/compiler/msvc.vim
#usr/share/vim/vim71/compiler/neato.vim
#usr/share/vim/vim71/compiler/onsgmls.vim
#usr/share/vim/vim71/compiler/pbx.vim
#usr/share/vim/vim71/compiler/perl.vim
#usr/share/vim/vim71/compiler/php.vim
#usr/share/vim/vim71/compiler/pyunit.vim
#usr/share/vim/vim71/compiler/rst.vim
#usr/share/vim/vim71/compiler/ruby.vim
#usr/share/vim/vim71/compiler/rubyunit.vim
#usr/share/vim/vim71/compiler/se.vim
#usr/share/vim/vim71/compiler/splint.vim
#usr/share/vim/vim71/compiler/tcl.vim
#usr/share/vim/vim71/compiler/tex.vim
#usr/share/vim/vim71/compiler/tidy.vim
#usr/share/vim/vim71/compiler/xmllint.vim
#usr/share/vim/vim71/compiler/xmlwf.vim
#usr/share/vim/vim71/delmenu.vim
#usr/share/vim/vim71/doc
#usr/share/vim/vim71/doc/ada.txt
#usr/share/vim/vim71/doc/arabic.txt
#usr/share/vim/vim71/doc/autocmd.txt
#usr/share/vim/vim71/doc/change.txt
#usr/share/vim/vim71/doc/cmdline.txt
#usr/share/vim/vim71/doc/debug.txt
#usr/share/vim/vim71/doc/debugger.txt
#usr/share/vim/vim71/doc/develop.txt
#usr/share/vim/vim71/doc/diff.txt
#usr/share/vim/vim71/doc/digraph.txt
#usr/share/vim/vim71/doc/editing.txt
#usr/share/vim/vim71/doc/eval.txt
#usr/share/vim/vim71/doc/farsi.txt
#usr/share/vim/vim71/doc/filetype.txt
#usr/share/vim/vim71/doc/fold.txt
#usr/share/vim/vim71/doc/gui.txt
#usr/share/vim/vim71/doc/gui_w16.txt
#usr/share/vim/vim71/doc/gui_w32.txt
#usr/share/vim/vim71/doc/gui_x11.txt
#usr/share/vim/vim71/doc/hangulin.txt
#usr/share/vim/vim71/doc/hebrew.txt
#usr/share/vim/vim71/doc/help.txt
#usr/share/vim/vim71/doc/howto.txt
#usr/share/vim/vim71/doc/if_cscop.txt
#usr/share/vim/vim71/doc/if_mzsch.txt
#usr/share/vim/vim71/doc/if_ole.txt
#usr/share/vim/vim71/doc/if_perl.txt
#usr/share/vim/vim71/doc/if_pyth.txt
#usr/share/vim/vim71/doc/if_ruby.txt
#usr/share/vim/vim71/doc/if_sniff.txt
#usr/share/vim/vim71/doc/if_tcl.txt
#usr/share/vim/vim71/doc/indent.txt
#usr/share/vim/vim71/doc/index.txt
#usr/share/vim/vim71/doc/insert.txt
#usr/share/vim/vim71/doc/intro.txt
#usr/share/vim/vim71/doc/map.txt
#usr/share/vim/vim71/doc/mbyte.txt
#usr/share/vim/vim71/doc/message.txt
#usr/share/vim/vim71/doc/mlang.txt
#usr/share/vim/vim71/doc/motion.txt
#usr/share/vim/vim71/doc/netbeans.txt
#usr/share/vim/vim71/doc/options.txt
#usr/share/vim/vim71/doc/os_390.txt
#usr/share/vim/vim71/doc/os_amiga.txt
#usr/share/vim/vim71/doc/os_beos.txt
#usr/share/vim/vim71/doc/os_dos.txt
#usr/share/vim/vim71/doc/os_mac.txt
#usr/share/vim/vim71/doc/os_mint.txt
#usr/share/vim/vim71/doc/os_msdos.txt
#usr/share/vim/vim71/doc/os_os2.txt
#usr/share/vim/vim71/doc/os_qnx.txt
#usr/share/vim/vim71/doc/os_risc.txt
#usr/share/vim/vim71/doc/os_unix.txt
#usr/share/vim/vim71/doc/os_vms.txt
#usr/share/vim/vim71/doc/os_win32.txt
#usr/share/vim/vim71/doc/pattern.txt
#usr/share/vim/vim71/doc/pi_getscript.txt
#usr/share/vim/vim71/doc/pi_gzip.txt
#usr/share/vim/vim71/doc/pi_netrw.txt
#usr/share/vim/vim71/doc/pi_paren.txt
#usr/share/vim/vim71/doc/pi_spec.txt
#usr/share/vim/vim71/doc/pi_tar.txt
#usr/share/vim/vim71/doc/pi_vimball.txt
#usr/share/vim/vim71/doc/pi_zip.txt
#usr/share/vim/vim71/doc/print.txt
#usr/share/vim/vim71/doc/quickfix.txt
#usr/share/vim/vim71/doc/quickref.txt
#usr/share/vim/vim71/doc/quotes.txt
#usr/share/vim/vim71/doc/recover.txt
#usr/share/vim/vim71/doc/remote.txt
#usr/share/vim/vim71/doc/repeat.txt
#usr/share/vim/vim71/doc/rileft.txt
#usr/share/vim/vim71/doc/russian.txt
#usr/share/vim/vim71/doc/scroll.txt
#usr/share/vim/vim71/doc/sign.txt
#usr/share/vim/vim71/doc/spell.txt
#usr/share/vim/vim71/doc/sponsor.txt
#usr/share/vim/vim71/doc/sql.txt
#usr/share/vim/vim71/doc/starting.txt
#usr/share/vim/vim71/doc/syntax.txt
#usr/share/vim/vim71/doc/tabpage.txt
#usr/share/vim/vim71/doc/tags
#usr/share/vim/vim71/doc/tagsrch.txt
#usr/share/vim/vim71/doc/term.txt
#usr/share/vim/vim71/doc/tips.txt
#usr/share/vim/vim71/doc/todo.txt
#usr/share/vim/vim71/doc/uganda.txt
#usr/share/vim/vim71/doc/undo.txt
#usr/share/vim/vim71/doc/usr_01.txt
#usr/share/vim/vim71/doc/usr_02.txt
#usr/share/vim/vim71/doc/usr_03.txt
#usr/share/vim/vim71/doc/usr_04.txt
#usr/share/vim/vim71/doc/usr_05.txt
#usr/share/vim/vim71/doc/usr_06.txt
#usr/share/vim/vim71/doc/usr_07.txt
#usr/share/vim/vim71/doc/usr_08.txt
#usr/share/vim/vim71/doc/usr_09.txt
#usr/share/vim/vim71/doc/usr_10.txt
#usr/share/vim/vim71/doc/usr_11.txt
#usr/share/vim/vim71/doc/usr_12.txt
#usr/share/vim/vim71/doc/usr_20.txt
#usr/share/vim/vim71/doc/usr_21.txt
#usr/share/vim/vim71/doc/usr_22.txt
#usr/share/vim/vim71/doc/usr_23.txt
#usr/share/vim/vim71/doc/usr_24.txt
#usr/share/vim/vim71/doc/usr_25.txt
#usr/share/vim/vim71/doc/usr_26.txt
#usr/share/vim/vim71/doc/usr_27.txt
#usr/share/vim/vim71/doc/usr_28.txt
#usr/share/vim/vim71/doc/usr_29.txt
#usr/share/vim/vim71/doc/usr_30.txt
#usr/share/vim/vim71/doc/usr_31.txt
#usr/share/vim/vim71/doc/usr_32.txt
#usr/share/vim/vim71/doc/usr_40.txt
#usr/share/vim/vim71/doc/usr_41.txt
#usr/share/vim/vim71/doc/usr_42.txt
#usr/share/vim/vim71/doc/usr_43.txt
#usr/share/vim/vim71/doc/usr_44.txt
#usr/share/vim/vim71/doc/usr_45.txt
#usr/share/vim/vim71/doc/usr_90.txt
#usr/share/vim/vim71/doc/usr_toc.txt
#usr/share/vim/vim71/doc/various.txt
#usr/share/vim/vim71/doc/version4.txt
#usr/share/vim/vim71/doc/version5.txt
#usr/share/vim/vim71/doc/version6.txt
#usr/share/vim/vim71/doc/version7.txt
#usr/share/vim/vim71/doc/vi_diff.txt
#usr/share/vim/vim71/doc/vim2html.pl
#usr/share/vim/vim71/doc/visual.txt
#usr/share/vim/vim71/doc/windows.txt
#usr/share/vim/vim71/doc/workshop.txt
#usr/share/vim/vim71/evim.vim
#usr/share/vim/vim71/filetype.vim
#usr/share/vim/vim71/ftoff.vim
#usr/share/vim/vim71/ftplugin
#usr/share/vim/vim71/ftplugin.vim
#usr/share/vim/vim71/ftplugin/AppendMatchGroup.vim
#usr/share/vim/vim71/ftplugin/README.txt
#usr/share/vim/vim71/ftplugin/a2ps.vim
#usr/share/vim/vim71/ftplugin/aap.vim
#usr/share/vim/vim71/ftplugin/abaqus.vim
#usr/share/vim/vim71/ftplugin/ada.vim
#usr/share/vim/vim71/ftplugin/alsaconf.vim
#usr/share/vim/vim71/ftplugin/ant.vim
#usr/share/vim/vim71/ftplugin/arch.vim
#usr/share/vim/vim71/ftplugin/art.vim
#usr/share/vim/vim71/ftplugin/aspvbs.vim
#usr/share/vim/vim71/ftplugin/automake.vim
#usr/share/vim/vim71/ftplugin/bdf.vim
#usr/share/vim/vim71/ftplugin/bst.vim
#usr/share/vim/vim71/ftplugin/btm.vim
#usr/share/vim/vim71/ftplugin/c.vim
#usr/share/vim/vim71/ftplugin/calendar.vim
#usr/share/vim/vim71/ftplugin/ch.vim
#usr/share/vim/vim71/ftplugin/changelog.vim
#usr/share/vim/vim71/ftplugin/cobol.vim
#usr/share/vim/vim71/ftplugin/conf.vim
#usr/share/vim/vim71/ftplugin/config.vim
#usr/share/vim/vim71/ftplugin/context.vim
#usr/share/vim/vim71/ftplugin/cpp.vim
#usr/share/vim/vim71/ftplugin/crm.vim
#usr/share/vim/vim71/ftplugin/cs.vim
#usr/share/vim/vim71/ftplugin/csc.vim
#usr/share/vim/vim71/ftplugin/csh.vim
#usr/share/vim/vim71/ftplugin/css.vim
#usr/share/vim/vim71/ftplugin/cvsrc.vim
#usr/share/vim/vim71/ftplugin/debchangelog.vim
#usr/share/vim/vim71/ftplugin/dictconf.vim
#usr/share/vim/vim71/ftplugin/dictdconf.vim
#usr/share/vim/vim71/ftplugin/diff.vim
#usr/share/vim/vim71/ftplugin/dircolors.vim
#usr/share/vim/vim71/ftplugin/dosbatch.vim
#usr/share/vim/vim71/ftplugin/dtd.vim
#usr/share/vim/vim71/ftplugin/elinks.vim
#usr/share/vim/vim71/ftplugin/eruby.vim
#usr/share/vim/vim71/ftplugin/eterm.vim
#usr/share/vim/vim71/ftplugin/fetchmail.vim
#usr/share/vim/vim71/ftplugin/flexwiki.vim
#usr/share/vim/vim71/ftplugin/fortran.vim
#usr/share/vim/vim71/ftplugin/fvwm.vim
#usr/share/vim/vim71/ftplugin/gpg.vim
#usr/share/vim/vim71/ftplugin/group.vim
#usr/share/vim/vim71/ftplugin/grub.vim
#usr/share/vim/vim71/ftplugin/hamster.vim
#usr/share/vim/vim71/ftplugin/haskell.vim
#usr/share/vim/vim71/ftplugin/help.vim
#usr/share/vim/vim71/ftplugin/html.vim
#usr/share/vim/vim71/ftplugin/htmldjango.vim
#usr/share/vim/vim71/ftplugin/indent.vim
#usr/share/vim/vim71/ftplugin/initex.vim
#usr/share/vim/vim71/ftplugin/ishd.vim
#usr/share/vim/vim71/ftplugin/java.vim
#usr/share/vim/vim71/ftplugin/javascript.vim
#usr/share/vim/vim71/ftplugin/jsp.vim
#usr/share/vim/vim71/ftplugin/kconfig.vim
#usr/share/vim/vim71/ftplugin/kwt.vim
#usr/share/vim/vim71/ftplugin/ld.vim
#usr/share/vim/vim71/ftplugin/lftp.vim
#usr/share/vim/vim71/ftplugin/libao.vim
#usr/share/vim/vim71/ftplugin/limits.vim
#usr/share/vim/vim71/ftplugin/lisp.vim
#usr/share/vim/vim71/ftplugin/loginaccess.vim
#usr/share/vim/vim71/ftplugin/logindefs.vim
#usr/share/vim/vim71/ftplugin/lprolog.vim
#usr/share/vim/vim71/ftplugin/lua.vim
#usr/share/vim/vim71/ftplugin/m4.vim
#usr/share/vim/vim71/ftplugin/mail.vim
#usr/share/vim/vim71/ftplugin/mailaliases.vim
#usr/share/vim/vim71/ftplugin/mailcap.vim
#usr/share/vim/vim71/ftplugin/make.vim
#usr/share/vim/vim71/ftplugin/man.vim
#usr/share/vim/vim71/ftplugin/manconf.vim
#usr/share/vim/vim71/ftplugin/matlab.vim
#usr/share/vim/vim71/ftplugin/mf.vim
#usr/share/vim/vim71/ftplugin/modconf.vim
#usr/share/vim/vim71/ftplugin/mp.vim
#usr/share/vim/vim71/ftplugin/mplayerconf.vim
#usr/share/vim/vim71/ftplugin/mrxvtrc.vim
#usr/share/vim/vim71/ftplugin/mupad.vim
#usr/share/vim/vim71/ftplugin/muttrc.vim
#usr/share/vim/vim71/ftplugin/nanorc.vim
#usr/share/vim/vim71/ftplugin/netrc.vim
#usr/share/vim/vim71/ftplugin/objc.vim
#usr/share/vim/vim71/ftplugin/ocaml.vim
#usr/share/vim/vim71/ftplugin/occam.vim
#usr/share/vim/vim71/ftplugin/pamconf.vim
#usr/share/vim/vim71/ftplugin/pascal.vim
#usr/share/vim/vim71/ftplugin/passwd.vim
#usr/share/vim/vim71/ftplugin/perl.vim
#usr/share/vim/vim71/ftplugin/php.vim
#usr/share/vim/vim71/ftplugin/pinfo.vim
#usr/share/vim/vim71/ftplugin/plaintex.vim
#usr/share/vim/vim71/ftplugin/postscr.vim
#usr/share/vim/vim71/ftplugin/procmail.vim
#usr/share/vim/vim71/ftplugin/prolog.vim
#usr/share/vim/vim71/ftplugin/protocols.vim
#usr/share/vim/vim71/ftplugin/pyrex.vim
#usr/share/vim/vim71/ftplugin/python.vim
#usr/share/vim/vim71/ftplugin/quake.vim
#usr/share/vim/vim71/ftplugin/racc.vim
#usr/share/vim/vim71/ftplugin/readline.vim
#usr/share/vim/vim71/ftplugin/rnc.vim
#usr/share/vim/vim71/ftplugin/rpl.vim
#usr/share/vim/vim71/ftplugin/rst.vim
#usr/share/vim/vim71/ftplugin/ruby.vim
#usr/share/vim/vim71/ftplugin/scheme.vim
#usr/share/vim/vim71/ftplugin/screen.vim
#usr/share/vim/vim71/ftplugin/sensors.vim
#usr/share/vim/vim71/ftplugin/services.vim
#usr/share/vim/vim71/ftplugin/setserial.vim
#usr/share/vim/vim71/ftplugin/sgml.vim
#usr/share/vim/vim71/ftplugin/sh.vim
#usr/share/vim/vim71/ftplugin/sieve.vim
#usr/share/vim/vim71/ftplugin/slpconf.vim
#usr/share/vim/vim71/ftplugin/slpreg.vim
#usr/share/vim/vim71/ftplugin/slpspi.vim
#usr/share/vim/vim71/ftplugin/spec.vim
#usr/share/vim/vim71/ftplugin/sql.vim
#usr/share/vim/vim71/ftplugin/sshconfig.vim
#usr/share/vim/vim71/ftplugin/sudoers.vim
#usr/share/vim/vim71/ftplugin/svg.vim
#usr/share/vim/vim71/ftplugin/sysctl.vim
#usr/share/vim/vim71/ftplugin/tcsh.vim
#usr/share/vim/vim71/ftplugin/terminfo.vim
#usr/share/vim/vim71/ftplugin/tex.vim
#usr/share/vim/vim71/ftplugin/udevconf.vim
#usr/share/vim/vim71/ftplugin/udevperm.vim
#usr/share/vim/vim71/ftplugin/udevrules.vim
#usr/share/vim/vim71/ftplugin/updatedb.vim
#usr/share/vim/vim71/ftplugin/vb.vim
#usr/share/vim/vim71/ftplugin/verilog.vim
#usr/share/vim/vim71/ftplugin/vhdl.vim
#usr/share/vim/vim71/ftplugin/vim.vim
#usr/share/vim/vim71/ftplugin/xdefaults.vim
#usr/share/vim/vim71/ftplugin/xf86conf.vim
#usr/share/vim/vim71/ftplugin/xhtml.vim
#usr/share/vim/vim71/ftplugin/xinetd.vim
#usr/share/vim/vim71/ftplugin/xml.vim
#usr/share/vim/vim71/ftplugin/xmodmap.vim
#usr/share/vim/vim71/ftplugin/xs.vim
#usr/share/vim/vim71/ftplugin/xsd.vim
#usr/share/vim/vim71/ftplugin/xslt.vim
#usr/share/vim/vim71/ftplugin/yaml.vim
#usr/share/vim/vim71/ftplugin/zsh.vim
#usr/share/vim/vim71/ftplugof.vim
#usr/share/vim/vim71/gvimrc_example.vim
#usr/share/vim/vim71/indent
#usr/share/vim/vim71/indent.vim
#usr/share/vim/vim71/indent/GenericIndent.vim
#usr/share/vim/vim71/indent/README.txt
#usr/share/vim/vim71/indent/aap.vim
#usr/share/vim/vim71/indent/ada.vim
#usr/share/vim/vim71/indent/ant.vim
#usr/share/vim/vim71/indent/automake.vim
#usr/share/vim/vim71/indent/awk.vim
#usr/share/vim/vim71/indent/bib.vim
#usr/share/vim/vim71/indent/bst.vim
#usr/share/vim/vim71/indent/c.vim
#usr/share/vim/vim71/indent/cdl.vim
#usr/share/vim/vim71/indent/ch.vim
#usr/share/vim/vim71/indent/changelog.vim
#usr/share/vim/vim71/indent/cmake.vim
#usr/share/vim/vim71/indent/cobol.vim
#usr/share/vim/vim71/indent/config.vim
#usr/share/vim/vim71/indent/cpp.vim
#usr/share/vim/vim71/indent/cs.vim
#usr/share/vim/vim71/indent/css.vim
#usr/share/vim/vim71/indent/d.vim
#usr/share/vim/vim71/indent/dictconf.vim
#usr/share/vim/vim71/indent/dictdconf.vim
#usr/share/vim/vim71/indent/docbk.vim
#usr/share/vim/vim71/indent/dylan.vim
#usr/share/vim/vim71/indent/eiffel.vim
#usr/share/vim/vim71/indent/eruby.vim
#usr/share/vim/vim71/indent/eterm.vim
#usr/share/vim/vim71/indent/fortran.vim
#usr/share/vim/vim71/indent/hamster.vim
#usr/share/vim/vim71/indent/html.vim
#usr/share/vim/vim71/indent/htmldjango.vim
#usr/share/vim/vim71/indent/idlang.vim
#usr/share/vim/vim71/indent/ishd.vim
#usr/share/vim/vim71/indent/java.vim
#usr/share/vim/vim71/indent/javascript.vim
#usr/share/vim/vim71/indent/jsp.vim
#usr/share/vim/vim71/indent/ld.vim
#usr/share/vim/vim71/indent/lisp.vim
#usr/share/vim/vim71/indent/lua.vim
#usr/share/vim/vim71/indent/make.vim
#usr/share/vim/vim71/indent/matlab.vim
#usr/share/vim/vim71/indent/mma.vim
#usr/share/vim/vim71/indent/mp.vim
#usr/share/vim/vim71/indent/mupad.vim
#usr/share/vim/vim71/indent/objc.vim
#usr/share/vim/vim71/indent/ocaml.vim
#usr/share/vim/vim71/indent/occam.vim
#usr/share/vim/vim71/indent/pascal.vim
#usr/share/vim/vim71/indent/perl.vim
#usr/share/vim/vim71/indent/php.vim
#usr/share/vim/vim71/indent/postscr.vim
#usr/share/vim/vim71/indent/pov.vim
#usr/share/vim/vim71/indent/prolog.vim
#usr/share/vim/vim71/indent/pyrex.vim
#usr/share/vim/vim71/indent/python.vim
#usr/share/vim/vim71/indent/readline.vim
#usr/share/vim/vim71/indent/rpl.vim
#usr/share/vim/vim71/indent/rst.vim
#usr/share/vim/vim71/indent/ruby.vim
#usr/share/vim/vim71/indent/scheme.vim
#usr/share/vim/vim71/indent/sdl.vim
#usr/share/vim/vim71/indent/sh.vim
#usr/share/vim/vim71/indent/sml.vim
#usr/share/vim/vim71/indent/sql.vim
#usr/share/vim/vim71/indent/sqlanywhere.vim
#usr/share/vim/vim71/indent/tcl.vim
#usr/share/vim/vim71/indent/tcsh.vim
#usr/share/vim/vim71/indent/tilde.vim
#usr/share/vim/vim71/indent/vb.vim
#usr/share/vim/vim71/indent/verilog.vim
#usr/share/vim/vim71/indent/vhdl.vim
#usr/share/vim/vim71/indent/vim.vim
#usr/share/vim/vim71/indent/xf86conf.vim
#usr/share/vim/vim71/indent/xhtml.vim
#usr/share/vim/vim71/indent/xinetd.vim
#usr/share/vim/vim71/indent/xml.vim
#usr/share/vim/vim71/indent/xsd.vim
#usr/share/vim/vim71/indent/xslt.vim
#usr/share/vim/vim71/indent/yacc.vim
#usr/share/vim/vim71/indent/zsh.vim
#usr/share/vim/vim71/indoff.vim
#usr/share/vim/vim71/keymap
#usr/share/vim/vim71/keymap/README.txt
#usr/share/vim/vim71/keymap/accents.vim
#usr/share/vim/vim71/keymap/arabic.vim
#usr/share/vim/vim71/keymap/arabic_utf-8.vim
#usr/share/vim/vim71/keymap/bulgarian-bds.vim
#usr/share/vim/vim71/keymap/bulgarian-phonetic.vim
#usr/share/vim/vim71/keymap/bulgarian.vim
#usr/share/vim/vim71/keymap/canfr-win.vim
#usr/share/vim/vim71/keymap/czech.vim
#usr/share/vim/vim71/keymap/czech_utf-8.vim
#usr/share/vim/vim71/keymap/esperanto.vim
#usr/share/vim/vim71/keymap/esperanto_utf-8.vim
#usr/share/vim/vim71/keymap/greek.vim
#usr/share/vim/vim71/keymap/greek_cp1253.vim
#usr/share/vim/vim71/keymap/greek_cp737.vim
#usr/share/vim/vim71/keymap/greek_iso-8859-7.vim
#usr/share/vim/vim71/keymap/greek_utf-8.vim
#usr/share/vim/vim71/keymap/hebrew.vim
#usr/share/vim/vim71/keymap/hebrew_cp1255.vim
#usr/share/vim/vim71/keymap/hebrew_iso-8859-8.vim
#usr/share/vim/vim71/keymap/hebrew_utf-8.vim
#usr/share/vim/vim71/keymap/hebrewp.vim
#usr/share/vim/vim71/keymap/hebrewp_cp1255.vim
#usr/share/vim/vim71/keymap/hebrewp_iso-8859-8.vim
#usr/share/vim/vim71/keymap/hebrewp_utf-8.vim
#usr/share/vim/vim71/keymap/kana.vim
#usr/share/vim/vim71/keymap/lithuanian-baltic.vim
#usr/share/vim/vim71/keymap/magyar_utf-8.vim
#usr/share/vim/vim71/keymap/mongolian_utf-8.vim
#usr/share/vim/vim71/keymap/persian-iranian_utf-8.vim
#usr/share/vim/vim71/keymap/persian.vim
#usr/share/vim/vim71/keymap/pinyin.vim
#usr/share/vim/vim71/keymap/polish-slash.vim
#usr/share/vim/vim71/keymap/polish-slash_cp1250.vim
#usr/share/vim/vim71/keymap/polish-slash_cp852.vim
#usr/share/vim/vim71/keymap/polish-slash_iso-8859-2.vim
#usr/share/vim/vim71/keymap/polish-slash_utf-8.vim
#usr/share/vim/vim71/keymap/russian-jcuken.vim
#usr/share/vim/vim71/keymap/russian-jcukenwin.vim
#usr/share/vim/vim71/keymap/russian-yawerty.vim
#usr/share/vim/vim71/keymap/serbian-latin.vim
#usr/share/vim/vim71/keymap/serbian-latin_utf-8.vim
#usr/share/vim/vim71/keymap/serbian.vim
#usr/share/vim/vim71/keymap/serbian_cp1250.vim
#usr/share/vim/vim71/keymap/serbian_cp1251.vim
#usr/share/vim/vim71/keymap/serbian_iso-8859-2.vim
#usr/share/vim/vim71/keymap/serbian_iso-8859-5.vim
#usr/share/vim/vim71/keymap/serbian_utf-8.vim
#usr/share/vim/vim71/keymap/sinhala-phonetic_utf-8.vim
#usr/share/vim/vim71/keymap/sinhala.vim
#usr/share/vim/vim71/keymap/slovak.vim
#usr/share/vim/vim71/keymap/slovak_cp1250.vim
#usr/share/vim/vim71/keymap/slovak_iso-8859-2.vim
#usr/share/vim/vim71/keymap/slovak_utf-8.vim
#usr/share/vim/vim71/keymap/tamil_tscii.vim
#usr/share/vim/vim71/keymap/thaana-phonetic_utf-8.vim
#usr/share/vim/vim71/keymap/thaana.vim
#usr/share/vim/vim71/keymap/ukrainian-jcuken.vim
#usr/share/vim/vim71/keymap/vietnamese-viqr_utf-8.vim
#usr/share/vim/vim71/lang
#usr/share/vim/vim71/lang/README.txt
#usr/share/vim/vim71/lang/menu_af.latin1.vim
#usr/share/vim/vim71/lang/menu_af.utf-8.vim
#usr/share/vim/vim71/lang/menu_af_af.latin1.vim
#usr/share/vim/vim71/lang/menu_af_af.utf-8.vim
#usr/share/vim/vim71/lang/menu_ca.latin1.vim
#usr/share/vim/vim71/lang/menu_ca.utf-8.vim
#usr/share/vim/vim71/lang/menu_ca_es.latin1.vim
#usr/share/vim/vim71/lang/menu_ca_es.utf-8.vim
#usr/share/vim/vim71/lang/menu_chinese(gb)_gb.936.vim
#usr/share/vim/vim71/lang/menu_chinese(taiwan)_taiwan.950.vim
#usr/share/vim/vim71/lang/menu_chinese_gb.936.vim
#usr/share/vim/vim71/lang/menu_chinese_taiwan.950.vim
#usr/share/vim/vim71/lang/menu_cs.cp1250.vim
#usr/share/vim/vim71/lang/menu_cs.latin1.vim
#usr/share/vim/vim71/lang/menu_cs_cz.cp1250.vim
#usr/share/vim/vim71/lang/menu_cs_cz.iso_8859-2.vim
#usr/share/vim/vim71/lang/menu_cs_cz.latin1.vim
#usr/share/vim/vim71/lang/menu_czech_czech_republic.1250.vim
#usr/share/vim/vim71/lang/menu_czech_czech_republic.1252.vim
#usr/share/vim/vim71/lang/menu_czech_czech_republic.ascii.vim
#usr/share/vim/vim71/lang/menu_de.latin1.vim
#usr/share/vim/vim71/lang/menu_de.utf-8.vim
#usr/share/vim/vim71/lang/menu_de_de.latin1.vim
#usr/share/vim/vim71/lang/menu_de_de.utf-8.vim
#usr/share/vim/vim71/lang/menu_en_gb.latin1.vim
#usr/share/vim/vim71/lang/menu_en_gb.utf-8.vim
#usr/share/vim/vim71/lang/menu_english_united_kingdom.1252.vim
#usr/share/vim/vim71/lang/menu_english_united_kingdom.ascii.vim
#usr/share/vim/vim71/lang/menu_es.latin1.vim
#usr/share/vim/vim71/lang/menu_es.utf-8.vim
#usr/share/vim/vim71/lang/menu_es_es.latin1.vim
#usr/share/vim/vim71/lang/menu_es_es.utf-8.vim
#usr/share/vim/vim71/lang/menu_fr.latin1.vim
#usr/share/vim/vim71/lang/menu_fr.utf-8.vim
#usr/share/vim/vim71/lang/menu_fr_fr.latin1.vim
#usr/share/vim/vim71/lang/menu_fr_fr.utf-8.vim
#usr/share/vim/vim71/lang/menu_french_france.1252.vim
#usr/share/vim/vim71/lang/menu_german_germany.1252.vim
#usr/share/vim/vim71/lang/menu_hu.iso_8859-2.vim
#usr/share/vim/vim71/lang/menu_hu.utf-8.vim
#usr/share/vim/vim71/lang/menu_hu_hu.iso_8859-2.vim
#usr/share/vim/vim71/lang/menu_hu_hu.utf-8.vim
#usr/share/vim/vim71/lang/menu_it.latin1.vim
#usr/share/vim/vim71/lang/menu_it.utf-8.vim
#usr/share/vim/vim71/lang/menu_it_it.latin1.vim
#usr/share/vim/vim71/lang/menu_it_it.utf-8.vim
#usr/share/vim/vim71/lang/menu_italian_italy.1252.vim
#usr/share/vim/vim71/lang/menu_ja.cp932.vim
#usr/share/vim/vim71/lang/menu_ja.euc-jp.vim
#usr/share/vim/vim71/lang/menu_ja.eucjp.vim
#usr/share/vim/vim71/lang/menu_ja.ujis.vim
#usr/share/vim/vim71/lang/menu_ja.utf-8.vim
#usr/share/vim/vim71/lang/menu_ja_jp.cp932.vim
#usr/share/vim/vim71/lang/menu_ja_jp.euc-jp.vim
#usr/share/vim/vim71/lang/menu_ja_jp.eucjp.vim
#usr/share/vim/vim71/lang/menu_ja_jp.ujis.vim
#usr/share/vim/vim71/lang/menu_ja_jp.utf-8.vim
#usr/share/vim/vim71/lang/menu_japanese_japan.932.vim
#usr/share/vim/vim71/lang/menu_ko.utf-8.vim
#usr/share/vim/vim71/lang/menu_ko_kr.euckr.vim
#usr/share/vim/vim71/lang/menu_ko_kr.utf-8.vim
#usr/share/vim/vim71/lang/menu_ko_kr.vim
#usr/share/vim/vim71/lang/menu_nl.latin1.vim
#usr/share/vim/vim71/lang/menu_nl.utf-8.vim
#usr/share/vim/vim71/lang/menu_nl_nl.latin1.vim
#usr/share/vim/vim71/lang/menu_nl_nl.utf-8.vim
#usr/share/vim/vim71/lang/menu_no.latin1.vim
#usr/share/vim/vim71/lang/menu_no.utf-8.vim
#usr/share/vim/vim71/lang/menu_no_no.latin1.vim
#usr/share/vim/vim71/lang/menu_no_no.utf-8.vim
#usr/share/vim/vim71/lang/menu_pl.cp1250.vim
#usr/share/vim/vim71/lang/menu_pl_pl.cp1250.vim
#usr/share/vim/vim71/lang/menu_pl_pl.iso_8859-2.vim
#usr/share/vim/vim71/lang/menu_pl_pl.utf-8.vim
#usr/share/vim/vim71/lang/menu_polish_poland.1250.vim
#usr/share/vim/vim71/lang/menu_pt_br.latin1.vim
#usr/share/vim/vim71/lang/menu_pt_br.utf-8.vim
#usr/share/vim/vim71/lang/menu_pt_br.vim
#usr/share/vim/vim71/lang/menu_pt_pt.latin1.vim
#usr/share/vim/vim71/lang/menu_pt_pt.utf-8.vim
#usr/share/vim/vim71/lang/menu_pt_pt.vim
#usr/share/vim/vim71/lang/menu_ru.utf-8.vim
#usr/share/vim/vim71/lang/menu_ru_ru.koi8-r.vim
#usr/share/vim/vim71/lang/menu_ru_ru.utf-8.vim
#usr/share/vim/vim71/lang/menu_ru_ru.vim
#usr/share/vim/vim71/lang/menu_sk.cp1250.vim
#usr/share/vim/vim71/lang/menu_sk_sk.1250.vim
#usr/share/vim/vim71/lang/menu_sk_sk.cp1250.vim
#usr/share/vim/vim71/lang/menu_sk_sk.iso_8859-2.vim
#usr/share/vim/vim71/lang/menu_sk_sk.vim
#usr/share/vim/vim71/lang/menu_sl_si.cp1250.vim
#usr/share/vim/vim71/lang/menu_sl_si.latin2.vim
#usr/share/vim/vim71/lang/menu_sl_si.utf-8.vim
#usr/share/vim/vim71/lang/menu_slovak_slovak_republic.1250.vim
#usr/share/vim/vim71/lang/menu_spanish_spain.850.vim
#usr/share/vim/vim71/lang/menu_sr.utf-8.vim
#usr/share/vim/vim71/lang/menu_sr_yu.ascii.vim
#usr/share/vim/vim71/lang/menu_sr_yu.iso_8859-2.vim
#usr/share/vim/vim71/lang/menu_sr_yu.iso_8859-5.vim
#usr/share/vim/vim71/lang/menu_sr_yu.utf-8.vim
#usr/share/vim/vim71/lang/menu_sv.latin1.vim
#usr/share/vim/vim71/lang/menu_sv.utf-8.vim
#usr/share/vim/vim71/lang/menu_sv_se.latin1.vim
#usr/share/vim/vim71/lang/menu_sv_se.utf-8.vim
#usr/share/vim/vim71/lang/menu_uk_ua.cp1251.vim
#usr/share/vim/vim71/lang/menu_uk_ua.koi8-u.vim
#usr/share/vim/vim71/lang/menu_vi_vn.vim
#usr/share/vim/vim71/lang/menu_zh.big5.vim
#usr/share/vim/vim71/lang/menu_zh.cp936.vim
#usr/share/vim/vim71/lang/menu_zh.cp950.vim
#usr/share/vim/vim71/lang/menu_zh.gb2312.vim
#usr/share/vim/vim71/lang/menu_zh_cn.18030.vim
#usr/share/vim/vim71/lang/menu_zh_cn.cp936.vim
#usr/share/vim/vim71/lang/menu_zh_cn.gb2312.vim
#usr/share/vim/vim71/lang/menu_zh_cn.gbk.vim
#usr/share/vim/vim71/lang/menu_zh_cn.utf-8.vim
#usr/share/vim/vim71/lang/menu_zh_tw.big5.vim
#usr/share/vim/vim71/lang/menu_zh_tw.cp950.vim
#usr/share/vim/vim71/lang/menu_zh_tw.utf-8.vim
#usr/share/vim/vim71/macros
#usr/share/vim/vim71/macros/README.txt
#usr/share/vim/vim71/macros/dvorak
#usr/share/vim/vim71/macros/editexisting.vim
#usr/share/vim/vim71/macros/hanoi
#usr/share/vim/vim71/macros/hanoi/click.me
#usr/share/vim/vim71/macros/hanoi/hanoi.vim
#usr/share/vim/vim71/macros/hanoi/poster
#usr/share/vim/vim71/macros/justify.vim
#usr/share/vim/vim71/macros/less.sh
#usr/share/vim/vim71/macros/less.vim
#usr/share/vim/vim71/macros/life
#usr/share/vim/vim71/macros/life/click.me
#usr/share/vim/vim71/macros/life/life.vim
#usr/share/vim/vim71/macros/matchit.txt
#usr/share/vim/vim71/macros/matchit.vim
#usr/share/vim/vim71/macros/maze
#usr/share/vim/vim71/macros/maze/Makefile
#usr/share/vim/vim71/macros/maze/README.txt
#usr/share/vim/vim71/macros/maze/main.aap
#usr/share/vim/vim71/macros/maze/maze.c
#usr/share/vim/vim71/macros/maze/maze_5.78
#usr/share/vim/vim71/macros/maze/maze_mac
#usr/share/vim/vim71/macros/maze/mazeansi.c
#usr/share/vim/vim71/macros/maze/mazeclean.c
#usr/share/vim/vim71/macros/maze/poster
#usr/share/vim/vim71/macros/shellmenu.vim
#usr/share/vim/vim71/macros/swapmous.vim
#usr/share/vim/vim71/macros/urm
#usr/share/vim/vim71/macros/urm/README.txt
#usr/share/vim/vim71/macros/urm/examples
#usr/share/vim/vim71/macros/urm/urm
#usr/share/vim/vim71/macros/urm/urm.vim
#usr/share/vim/vim71/menu.vim
#usr/share/vim/vim71/mswin.vim
#usr/share/vim/vim71/optwin.vim
#usr/share/vim/vim71/plugin
#usr/share/vim/vim71/plugin/README.txt
#usr/share/vim/vim71/plugin/getscriptPlugin.vim
#usr/share/vim/vim71/plugin/gzip.vim
#usr/share/vim/vim71/plugin/matchparen.vim
#usr/share/vim/vim71/plugin/netrwPlugin.vim
#usr/share/vim/vim71/plugin/rrhelper.vim
#usr/share/vim/vim71/plugin/spellfile.vim
#usr/share/vim/vim71/plugin/tarPlugin.vim
#usr/share/vim/vim71/plugin/tohtml.vim
#usr/share/vim/vim71/plugin/vimballPlugin.vim
#usr/share/vim/vim71/plugin/zipPlugin.vim
#usr/share/vim/vim71/print
#usr/share/vim/vim71/print/ascii.ps
#usr/share/vim/vim71/print/cidfont.ps
#usr/share/vim/vim71/print/cns_roman.ps
#usr/share/vim/vim71/print/cp1250.ps
#usr/share/vim/vim71/print/cp1251.ps
#usr/share/vim/vim71/print/cp1252.ps
#usr/share/vim/vim71/print/cp1253.ps
#usr/share/vim/vim71/print/cp1254.ps
#usr/share/vim/vim71/print/cp1255.ps
#usr/share/vim/vim71/print/cp1257.ps
#usr/share/vim/vim71/print/dec-mcs.ps
#usr/share/vim/vim71/print/ebcdic-uk.ps
#usr/share/vim/vim71/print/gb_roman.ps
#usr/share/vim/vim71/print/hp-roman8.ps
#usr/share/vim/vim71/print/iso-8859-10.ps
#usr/share/vim/vim71/print/iso-8859-11.ps
#usr/share/vim/vim71/print/iso-8859-13.ps
#usr/share/vim/vim71/print/iso-8859-14.ps
#usr/share/vim/vim71/print/iso-8859-15.ps
#usr/share/vim/vim71/print/iso-8859-2.ps
#usr/share/vim/vim71/print/iso-8859-3.ps
#usr/share/vim/vim71/print/iso-8859-4.ps
#usr/share/vim/vim71/print/iso-8859-5.ps
#usr/share/vim/vim71/print/iso-8859-7.ps
#usr/share/vim/vim71/print/iso-8859-8.ps
#usr/share/vim/vim71/print/iso-8859-9.ps
#usr/share/vim/vim71/print/jis_roman.ps
#usr/share/vim/vim71/print/koi8-r.ps
#usr/share/vim/vim71/print/koi8-u.ps
#usr/share/vim/vim71/print/ks_roman.ps
#usr/share/vim/vim71/print/latin1.ps
#usr/share/vim/vim71/print/mac-roman.ps
#usr/share/vim/vim71/print/prolog.ps
#usr/share/vim/vim71/scripts.vim
#usr/share/vim/vim71/spell
#usr/share/vim/vim71/spell/cleanadd.vim
#usr/share/vim/vim71/spell/en.ascii.spl
#usr/share/vim/vim71/spell/en.ascii.sug
#usr/share/vim/vim71/spell/en.latin1.spl
#usr/share/vim/vim71/spell/en.latin1.sug
#usr/share/vim/vim71/spell/en.utf-8.spl
#usr/share/vim/vim71/spell/en.utf-8.sug
#usr/share/vim/vim71/spell/he.vim
#usr/share/vim/vim71/spell/yi.vim
#usr/share/vim/vim71/synmenu.vim
#usr/share/vim/vim71/syntax
#usr/share/vim/vim71/syntax/2html.vim
#usr/share/vim/vim71/syntax/README.txt
#usr/share/vim/vim71/syntax/a2ps.vim
#usr/share/vim/vim71/syntax/a65.vim
#usr/share/vim/vim71/syntax/aap.vim
#usr/share/vim/vim71/syntax/abap.vim
#usr/share/vim/vim71/syntax/abaqus.vim
#usr/share/vim/vim71/syntax/abc.vim
#usr/share/vim/vim71/syntax/abel.vim
#usr/share/vim/vim71/syntax/acedb.vim
#usr/share/vim/vim71/syntax/ada.vim
#usr/share/vim/vim71/syntax/aflex.vim
#usr/share/vim/vim71/syntax/ahdl.vim
#usr/share/vim/vim71/syntax/alsaconf.vim
#usr/share/vim/vim71/syntax/amiga.vim
#usr/share/vim/vim71/syntax/aml.vim
#usr/share/vim/vim71/syntax/ampl.vim
#usr/share/vim/vim71/syntax/ant.vim
#usr/share/vim/vim71/syntax/antlr.vim
#usr/share/vim/vim71/syntax/apache.vim
#usr/share/vim/vim71/syntax/apachestyle.vim
#usr/share/vim/vim71/syntax/arch.vim
#usr/share/vim/vim71/syntax/art.vim
#usr/share/vim/vim71/syntax/asm.vim
#usr/share/vim/vim71/syntax/asm68k.vim
#usr/share/vim/vim71/syntax/asmh8300.vim
#usr/share/vim/vim71/syntax/asn.vim
#usr/share/vim/vim71/syntax/aspperl.vim
#usr/share/vim/vim71/syntax/aspvbs.vim
#usr/share/vim/vim71/syntax/asterisk.vim
#usr/share/vim/vim71/syntax/asteriskvm.vim
#usr/share/vim/vim71/syntax/atlas.vim
#usr/share/vim/vim71/syntax/autohotkey.vim
#usr/share/vim/vim71/syntax/autoit.vim
#usr/share/vim/vim71/syntax/automake.vim
#usr/share/vim/vim71/syntax/ave.vim
#usr/share/vim/vim71/syntax/awk.vim
#usr/share/vim/vim71/syntax/ayacc.vim
#usr/share/vim/vim71/syntax/b.vim
#usr/share/vim/vim71/syntax/baan.vim
#usr/share/vim/vim71/syntax/basic.vim
#usr/share/vim/vim71/syntax/bc.vim
#usr/share/vim/vim71/syntax/bdf.vim
#usr/share/vim/vim71/syntax/bib.vim
#usr/share/vim/vim71/syntax/bindzone.vim
#usr/share/vim/vim71/syntax/blank.vim
#usr/share/vim/vim71/syntax/bst.vim
#usr/share/vim/vim71/syntax/btm.vim
#usr/share/vim/vim71/syntax/bzr.vim
#usr/share/vim/vim71/syntax/c.vim
#usr/share/vim/vim71/syntax/calendar.vim
#usr/share/vim/vim71/syntax/catalog.vim
#usr/share/vim/vim71/syntax/cdl.vim
#usr/share/vim/vim71/syntax/cdrtoc.vim
#usr/share/vim/vim71/syntax/cf.vim
#usr/share/vim/vim71/syntax/cfg.vim
#usr/share/vim/vim71/syntax/ch.vim
#usr/share/vim/vim71/syntax/change.vim
#usr/share/vim/vim71/syntax/changelog.vim
#usr/share/vim/vim71/syntax/chaskell.vim
#usr/share/vim/vim71/syntax/cheetah.vim
#usr/share/vim/vim71/syntax/chill.vim
#usr/share/vim/vim71/syntax/chordpro.vim
#usr/share/vim/vim71/syntax/cl.vim
#usr/share/vim/vim71/syntax/clean.vim
#usr/share/vim/vim71/syntax/clipper.vim
#usr/share/vim/vim71/syntax/cmake.vim
#usr/share/vim/vim71/syntax/cmusrc.vim
#usr/share/vim/vim71/syntax/cobol.vim
#usr/share/vim/vim71/syntax/colortest.vim
#usr/share/vim/vim71/syntax/conaryrecipe.vim
#usr/share/vim/vim71/syntax/conf.vim
#usr/share/vim/vim71/syntax/config.vim
#usr/share/vim/vim71/syntax/context.vim
#usr/share/vim/vim71/syntax/cpp.vim
#usr/share/vim/vim71/syntax/crm.vim
#usr/share/vim/vim71/syntax/crontab.vim
#usr/share/vim/vim71/syntax/cs.vim
#usr/share/vim/vim71/syntax/csc.vim
#usr/share/vim/vim71/syntax/csh.vim
#usr/share/vim/vim71/syntax/csp.vim
#usr/share/vim/vim71/syntax/css.vim
#usr/share/vim/vim71/syntax/cterm.vim
#usr/share/vim/vim71/syntax/ctrlh.vim
#usr/share/vim/vim71/syntax/cupl.vim
#usr/share/vim/vim71/syntax/cuplsim.vim
#usr/share/vim/vim71/syntax/cvs.vim
#usr/share/vim/vim71/syntax/cvsrc.vim
#usr/share/vim/vim71/syntax/cweb.vim
#usr/share/vim/vim71/syntax/cynlib.vim
#usr/share/vim/vim71/syntax/cynpp.vim
#usr/share/vim/vim71/syntax/d.vim
#usr/share/vim/vim71/syntax/dcd.vim
#usr/share/vim/vim71/syntax/dcl.vim
#usr/share/vim/vim71/syntax/debchangelog.vim
#usr/share/vim/vim71/syntax/debcontrol.vim
#usr/share/vim/vim71/syntax/debsources.vim
#usr/share/vim/vim71/syntax/def.vim
#usr/share/vim/vim71/syntax/desc.vim
#usr/share/vim/vim71/syntax/desktop.vim
#usr/share/vim/vim71/syntax/dictconf.vim
#usr/share/vim/vim71/syntax/dictdconf.vim
#usr/share/vim/vim71/syntax/diff.vim
#usr/share/vim/vim71/syntax/dircolors.vim
#usr/share/vim/vim71/syntax/diva.vim
#usr/share/vim/vim71/syntax/django.vim
#usr/share/vim/vim71/syntax/dns.vim
#usr/share/vim/vim71/syntax/docbk.vim
#usr/share/vim/vim71/syntax/docbksgml.vim
#usr/share/vim/vim71/syntax/docbkxml.vim
#usr/share/vim/vim71/syntax/dosbatch.vim
#usr/share/vim/vim71/syntax/dosini.vim
#usr/share/vim/vim71/syntax/dot.vim
#usr/share/vim/vim71/syntax/doxygen.vim
#usr/share/vim/vim71/syntax/dracula.vim
#usr/share/vim/vim71/syntax/dsl.vim
#usr/share/vim/vim71/syntax/dtd.vim
#usr/share/vim/vim71/syntax/dtml.vim
#usr/share/vim/vim71/syntax/dylan.vim
#usr/share/vim/vim71/syntax/dylanintr.vim
#usr/share/vim/vim71/syntax/dylanlid.vim
#usr/share/vim/vim71/syntax/ecd.vim
#usr/share/vim/vim71/syntax/edif.vim
#usr/share/vim/vim71/syntax/eiffel.vim
#usr/share/vim/vim71/syntax/elf.vim
#usr/share/vim/vim71/syntax/elinks.vim
#usr/share/vim/vim71/syntax/elmfilt.vim
#usr/share/vim/vim71/syntax/erlang.vim
#usr/share/vim/vim71/syntax/eruby.vim
#usr/share/vim/vim71/syntax/esmtprc.vim
#usr/share/vim/vim71/syntax/esqlc.vim
#usr/share/vim/vim71/syntax/esterel.vim
#usr/share/vim/vim71/syntax/eterm.vim
#usr/share/vim/vim71/syntax/eviews.vim
#usr/share/vim/vim71/syntax/exim.vim
#usr/share/vim/vim71/syntax/expect.vim
#usr/share/vim/vim71/syntax/exports.vim
#usr/share/vim/vim71/syntax/fasm.vim
#usr/share/vim/vim71/syntax/fdcc.vim
#usr/share/vim/vim71/syntax/fetchmail.vim
#usr/share/vim/vim71/syntax/fgl.vim
#usr/share/vim/vim71/syntax/flexwiki.vim
#usr/share/vim/vim71/syntax/focexec.vim
#usr/share/vim/vim71/syntax/form.vim
#usr/share/vim/vim71/syntax/forth.vim
#usr/share/vim/vim71/syntax/fortran.vim
#usr/share/vim/vim71/syntax/foxpro.vim
#usr/share/vim/vim71/syntax/framescript.vim
#usr/share/vim/vim71/syntax/freebasic.vim
#usr/share/vim/vim71/syntax/fstab.vim
#usr/share/vim/vim71/syntax/fvwm.vim
#usr/share/vim/vim71/syntax/fvwm2m4.vim
#usr/share/vim/vim71/syntax/gdb.vim
#usr/share/vim/vim71/syntax/gdmo.vim
#usr/share/vim/vim71/syntax/gedcom.vim
#usr/share/vim/vim71/syntax/gkrellmrc.vim
#usr/share/vim/vim71/syntax/gnuplot.vim
#usr/share/vim/vim71/syntax/gp.vim
#usr/share/vim/vim71/syntax/gpg.vim
#usr/share/vim/vim71/syntax/grads.vim
#usr/share/vim/vim71/syntax/gretl.vim
#usr/share/vim/vim71/syntax/groff.vim
#usr/share/vim/vim71/syntax/groovy.vim
#usr/share/vim/vim71/syntax/group.vim
#usr/share/vim/vim71/syntax/grub.vim
#usr/share/vim/vim71/syntax/gsp.vim
#usr/share/vim/vim71/syntax/gtkrc.vim
#usr/share/vim/vim71/syntax/hamster.vim
#usr/share/vim/vim71/syntax/haskell.vim
#usr/share/vim/vim71/syntax/hb.vim
#usr/share/vim/vim71/syntax/help.vim
#usr/share/vim/vim71/syntax/hercules.vim
#usr/share/vim/vim71/syntax/hex.vim
#usr/share/vim/vim71/syntax/hitest.vim
#usr/share/vim/vim71/syntax/hog.vim
#usr/share/vim/vim71/syntax/html.vim
#usr/share/vim/vim71/syntax/htmlcheetah.vim
#usr/share/vim/vim71/syntax/htmldjango.vim
#usr/share/vim/vim71/syntax/htmlm4.vim
#usr/share/vim/vim71/syntax/htmlos.vim
#usr/share/vim/vim71/syntax/ia64.vim
#usr/share/vim/vim71/syntax/ibasic.vim
#usr/share/vim/vim71/syntax/icemenu.vim
#usr/share/vim/vim71/syntax/icon.vim
#usr/share/vim/vim71/syntax/idl.vim
#usr/share/vim/vim71/syntax/idlang.vim
#usr/share/vim/vim71/syntax/indent.vim
#usr/share/vim/vim71/syntax/inform.vim
#usr/share/vim/vim71/syntax/initex.vim
#usr/share/vim/vim71/syntax/initng.vim
#usr/share/vim/vim71/syntax/inittab.vim
#usr/share/vim/vim71/syntax/ipfilter.vim
#usr/share/vim/vim71/syntax/ishd.vim
#usr/share/vim/vim71/syntax/iss.vim
#usr/share/vim/vim71/syntax/ist.vim
#usr/share/vim/vim71/syntax/jal.vim
#usr/share/vim/vim71/syntax/jam.vim
#usr/share/vim/vim71/syntax/jargon.vim
#usr/share/vim/vim71/syntax/java.vim
#usr/share/vim/vim71/syntax/javacc.vim
#usr/share/vim/vim71/syntax/javascript.vim
#usr/share/vim/vim71/syntax/jess.vim
#usr/share/vim/vim71/syntax/jgraph.vim
#usr/share/vim/vim71/syntax/jproperties.vim
#usr/share/vim/vim71/syntax/jsp.vim
#usr/share/vim/vim71/syntax/kconfig.vim
#usr/share/vim/vim71/syntax/kix.vim
#usr/share/vim/vim71/syntax/kscript.vim
#usr/share/vim/vim71/syntax/kwt.vim
#usr/share/vim/vim71/syntax/lace.vim
#usr/share/vim/vim71/syntax/latte.vim
#usr/share/vim/vim71/syntax/ld.vim
#usr/share/vim/vim71/syntax/ldapconf.vim
#usr/share/vim/vim71/syntax/ldif.vim
#usr/share/vim/vim71/syntax/lex.vim
#usr/share/vim/vim71/syntax/lftp.vim
#usr/share/vim/vim71/syntax/lhaskell.vim
#usr/share/vim/vim71/syntax/libao.vim
#usr/share/vim/vim71/syntax/lifelines.vim
#usr/share/vim/vim71/syntax/lilo.vim
#usr/share/vim/vim71/syntax/limits.vim
#usr/share/vim/vim71/syntax/lisp.vim
#usr/share/vim/vim71/syntax/lite.vim
#usr/share/vim/vim71/syntax/litestep.vim
#usr/share/vim/vim71/syntax/loginaccess.vim
#usr/share/vim/vim71/syntax/logindefs.vim
#usr/share/vim/vim71/syntax/logtalk.vim
#usr/share/vim/vim71/syntax/lotos.vim
#usr/share/vim/vim71/syntax/lout.vim
#usr/share/vim/vim71/syntax/lpc.vim
#usr/share/vim/vim71/syntax/lprolog.vim
#usr/share/vim/vim71/syntax/lscript.vim
#usr/share/vim/vim71/syntax/lss.vim
#usr/share/vim/vim71/syntax/lua.vim
#usr/share/vim/vim71/syntax/lynx.vim
#usr/share/vim/vim71/syntax/m4.vim
#usr/share/vim/vim71/syntax/mail.vim
#usr/share/vim/vim71/syntax/mailaliases.vim
#usr/share/vim/vim71/syntax/mailcap.vim
#usr/share/vim/vim71/syntax/make.vim
#usr/share/vim/vim71/syntax/man.vim
#usr/share/vim/vim71/syntax/manconf.vim
#usr/share/vim/vim71/syntax/manual.vim
#usr/share/vim/vim71/syntax/maple.vim
#usr/share/vim/vim71/syntax/masm.vim
#usr/share/vim/vim71/syntax/mason.vim
#usr/share/vim/vim71/syntax/master.vim
#usr/share/vim/vim71/syntax/matlab.vim
#usr/share/vim/vim71/syntax/maxima.vim
#usr/share/vim/vim71/syntax/mel.vim
#usr/share/vim/vim71/syntax/messages.vim
#usr/share/vim/vim71/syntax/mf.vim
#usr/share/vim/vim71/syntax/mgl.vim
#usr/share/vim/vim71/syntax/mgp.vim
#usr/share/vim/vim71/syntax/mib.vim
#usr/share/vim/vim71/syntax/mma.vim
#usr/share/vim/vim71/syntax/mmix.vim
#usr/share/vim/vim71/syntax/modconf.vim
#usr/share/vim/vim71/syntax/model.vim
#usr/share/vim/vim71/syntax/modsim3.vim
#usr/share/vim/vim71/syntax/modula2.vim
#usr/share/vim/vim71/syntax/modula3.vim
#usr/share/vim/vim71/syntax/monk.vim
#usr/share/vim/vim71/syntax/moo.vim
#usr/share/vim/vim71/syntax/mp.vim
#usr/share/vim/vim71/syntax/mplayerconf.vim
#usr/share/vim/vim71/syntax/mrxvtrc.vim
#usr/share/vim/vim71/syntax/msidl.vim
#usr/share/vim/vim71/syntax/msql.vim
#usr/share/vim/vim71/syntax/mupad.vim
#usr/share/vim/vim71/syntax/mush.vim
#usr/share/vim/vim71/syntax/muttrc.vim
#usr/share/vim/vim71/syntax/mysql.vim
#usr/share/vim/vim71/syntax/named.vim
#usr/share/vim/vim71/syntax/nanorc.vim
#usr/share/vim/vim71/syntax/nasm.vim
#usr/share/vim/vim71/syntax/nastran.vim
#usr/share/vim/vim71/syntax/natural.vim
#usr/share/vim/vim71/syntax/ncf.vim
#usr/share/vim/vim71/syntax/netrc.vim
#usr/share/vim/vim71/syntax/netrw.vim
#usr/share/vim/vim71/syntax/nosyntax.vim
#usr/share/vim/vim71/syntax/nqc.vim
#usr/share/vim/vim71/syntax/nroff.vim
#usr/share/vim/vim71/syntax/nsis.vim
#usr/share/vim/vim71/syntax/objc.vim
#usr/share/vim/vim71/syntax/objcpp.vim
#usr/share/vim/vim71/syntax/ocaml.vim
#usr/share/vim/vim71/syntax/occam.vim
#usr/share/vim/vim71/syntax/omnimark.vim
#usr/share/vim/vim71/syntax/openroad.vim
#usr/share/vim/vim71/syntax/opl.vim
#usr/share/vim/vim71/syntax/ora.vim
#usr/share/vim/vim71/syntax/pamconf.vim
#usr/share/vim/vim71/syntax/papp.vim
#usr/share/vim/vim71/syntax/pascal.vim
#usr/share/vim/vim71/syntax/passwd.vim
#usr/share/vim/vim71/syntax/pcap.vim
#usr/share/vim/vim71/syntax/pccts.vim
#usr/share/vim/vim71/syntax/perl.vim
#usr/share/vim/vim71/syntax/pf.vim
#usr/share/vim/vim71/syntax/pfmain.vim
#usr/share/vim/vim71/syntax/php.vim
#usr/share/vim/vim71/syntax/phtml.vim
#usr/share/vim/vim71/syntax/pic.vim
#usr/share/vim/vim71/syntax/pike.vim
#usr/share/vim/vim71/syntax/pilrc.vim
#usr/share/vim/vim71/syntax/pine.vim
#usr/share/vim/vim71/syntax/pinfo.vim
#usr/share/vim/vim71/syntax/plaintex.vim
#usr/share/vim/vim71/syntax/plm.vim
#usr/share/vim/vim71/syntax/plp.vim
#usr/share/vim/vim71/syntax/plsql.vim
#usr/share/vim/vim71/syntax/po.vim
#usr/share/vim/vim71/syntax/pod.vim
#usr/share/vim/vim71/syntax/postscr.vim
#usr/share/vim/vim71/syntax/pov.vim
#usr/share/vim/vim71/syntax/povini.vim
#usr/share/vim/vim71/syntax/ppd.vim
#usr/share/vim/vim71/syntax/ppwiz.vim
#usr/share/vim/vim71/syntax/prescribe.vim
#usr/share/vim/vim71/syntax/privoxy.vim
#usr/share/vim/vim71/syntax/procmail.vim
#usr/share/vim/vim71/syntax/progress.vim
#usr/share/vim/vim71/syntax/prolog.vim
#usr/share/vim/vim71/syntax/protocols.vim
#usr/share/vim/vim71/syntax/psf.vim
#usr/share/vim/vim71/syntax/ptcap.vim
#usr/share/vim/vim71/syntax/purifylog.vim
#usr/share/vim/vim71/syntax/pyrex.vim
#usr/share/vim/vim71/syntax/python.vim
#usr/share/vim/vim71/syntax/qf.vim
#usr/share/vim/vim71/syntax/quake.vim
#usr/share/vim/vim71/syntax/r.vim
#usr/share/vim/vim71/syntax/racc.vim
#usr/share/vim/vim71/syntax/radiance.vim
#usr/share/vim/vim71/syntax/ratpoison.vim
#usr/share/vim/vim71/syntax/rc.vim
#usr/share/vim/vim71/syntax/rcs.vim
#usr/share/vim/vim71/syntax/rcslog.vim
#usr/share/vim/vim71/syntax/readline.vim
#usr/share/vim/vim71/syntax/rebol.vim
#usr/share/vim/vim71/syntax/registry.vim
#usr/share/vim/vim71/syntax/remind.vim
#usr/share/vim/vim71/syntax/resolv.vim
#usr/share/vim/vim71/syntax/rexx.vim
#usr/share/vim/vim71/syntax/rhelp.vim
#usr/share/vim/vim71/syntax/rib.vim
#usr/share/vim/vim71/syntax/rnc.vim
#usr/share/vim/vim71/syntax/rnoweb.vim
#usr/share/vim/vim71/syntax/robots.vim
#usr/share/vim/vim71/syntax/rpcgen.vim
#usr/share/vim/vim71/syntax/rpl.vim
#usr/share/vim/vim71/syntax/rst.vim
#usr/share/vim/vim71/syntax/rtf.vim
#usr/share/vim/vim71/syntax/ruby.vim
#usr/share/vim/vim71/syntax/samba.vim
#usr/share/vim/vim71/syntax/sas.vim
#usr/share/vim/vim71/syntax/sather.vim
#usr/share/vim/vim71/syntax/scheme.vim
#usr/share/vim/vim71/syntax/scilab.vim
#usr/share/vim/vim71/syntax/screen.vim
#usr/share/vim/vim71/syntax/sd.vim
#usr/share/vim/vim71/syntax/sdl.vim
#usr/share/vim/vim71/syntax/sed.vim
#usr/share/vim/vim71/syntax/sendpr.vim
#usr/share/vim/vim71/syntax/sensors.vim
#usr/share/vim/vim71/syntax/services.vim
#usr/share/vim/vim71/syntax/setserial.vim
#usr/share/vim/vim71/syntax/sgml.vim
#usr/share/vim/vim71/syntax/sgmldecl.vim
#usr/share/vim/vim71/syntax/sgmllnx.vim
#usr/share/vim/vim71/syntax/sh.vim
#usr/share/vim/vim71/syntax/sicad.vim
#usr/share/vim/vim71/syntax/sieve.vim
#usr/share/vim/vim71/syntax/simula.vim
#usr/share/vim/vim71/syntax/sinda.vim
#usr/share/vim/vim71/syntax/sindacmp.vim
#usr/share/vim/vim71/syntax/sindaout.vim
#usr/share/vim/vim71/syntax/sisu.vim
#usr/share/vim/vim71/syntax/skill.vim
#usr/share/vim/vim71/syntax/sl.vim
#usr/share/vim/vim71/syntax/slang.vim
#usr/share/vim/vim71/syntax/slice.vim
#usr/share/vim/vim71/syntax/slpconf.vim
#usr/share/vim/vim71/syntax/slpreg.vim
#usr/share/vim/vim71/syntax/slpspi.vim
#usr/share/vim/vim71/syntax/slrnrc.vim
#usr/share/vim/vim71/syntax/slrnsc.vim
#usr/share/vim/vim71/syntax/sm.vim
#usr/share/vim/vim71/syntax/smarty.vim
#usr/share/vim/vim71/syntax/smcl.vim
#usr/share/vim/vim71/syntax/smil.vim
#usr/share/vim/vim71/syntax/smith.vim
#usr/share/vim/vim71/syntax/sml.vim
#usr/share/vim/vim71/syntax/snnsnet.vim
#usr/share/vim/vim71/syntax/snnspat.vim
#usr/share/vim/vim71/syntax/snnsres.vim
#usr/share/vim/vim71/syntax/snobol4.vim
#usr/share/vim/vim71/syntax/spec.vim
#usr/share/vim/vim71/syntax/specman.vim
#usr/share/vim/vim71/syntax/spice.vim
#usr/share/vim/vim71/syntax/splint.vim
#usr/share/vim/vim71/syntax/spup.vim
#usr/share/vim/vim71/syntax/spyce.vim
#usr/share/vim/vim71/syntax/sql.vim
#usr/share/vim/vim71/syntax/sqlanywhere.vim
#usr/share/vim/vim71/syntax/sqlforms.vim
#usr/share/vim/vim71/syntax/sqlinformix.vim
#usr/share/vim/vim71/syntax/sqlj.vim
#usr/share/vim/vim71/syntax/sqloracle.vim
#usr/share/vim/vim71/syntax/sqr.vim
#usr/share/vim/vim71/syntax/squid.vim
#usr/share/vim/vim71/syntax/sshconfig.vim
#usr/share/vim/vim71/syntax/sshdconfig.vim
#usr/share/vim/vim71/syntax/st.vim
#usr/share/vim/vim71/syntax/stata.vim
#usr/share/vim/vim71/syntax/stp.vim
#usr/share/vim/vim71/syntax/strace.vim
#usr/share/vim/vim71/syntax/sudoers.vim
#usr/share/vim/vim71/syntax/svn.vim
#usr/share/vim/vim71/syntax/syncolor.vim
#usr/share/vim/vim71/syntax/synload.vim
#usr/share/vim/vim71/syntax/syntax.vim
#usr/share/vim/vim71/syntax/sysctl.vim
#usr/share/vim/vim71/syntax/tads.vim
#usr/share/vim/vim71/syntax/tags.vim
#usr/share/vim/vim71/syntax/tak.vim
#usr/share/vim/vim71/syntax/takcmp.vim
#usr/share/vim/vim71/syntax/takout.vim
#usr/share/vim/vim71/syntax/tar.vim
#usr/share/vim/vim71/syntax/tasm.vim
#usr/share/vim/vim71/syntax/tcl.vim
#usr/share/vim/vim71/syntax/tcsh.vim
#usr/share/vim/vim71/syntax/terminfo.vim
#usr/share/vim/vim71/syntax/tex.vim
#usr/share/vim/vim71/syntax/texinfo.vim
#usr/share/vim/vim71/syntax/texmf.vim
#usr/share/vim/vim71/syntax/tf.vim
#usr/share/vim/vim71/syntax/tidy.vim
#usr/share/vim/vim71/syntax/tilde.vim
#usr/share/vim/vim71/syntax/tli.vim
#usr/share/vim/vim71/syntax/tpp.vim
#usr/share/vim/vim71/syntax/trasys.vim
#usr/share/vim/vim71/syntax/trustees.vim
#usr/share/vim/vim71/syntax/tsalt.vim
#usr/share/vim/vim71/syntax/tsscl.vim
#usr/share/vim/vim71/syntax/tssgm.vim
#usr/share/vim/vim71/syntax/tssop.vim
#usr/share/vim/vim71/syntax/uc.vim
#usr/share/vim/vim71/syntax/udevconf.vim
#usr/share/vim/vim71/syntax/udevperm.vim
#usr/share/vim/vim71/syntax/udevrules.vim
#usr/share/vim/vim71/syntax/uil.vim
#usr/share/vim/vim71/syntax/updatedb.vim
#usr/share/vim/vim71/syntax/valgrind.vim
#usr/share/vim/vim71/syntax/vb.vim
#usr/share/vim/vim71/syntax/vera.vim
#usr/share/vim/vim71/syntax/verilog.vim
#usr/share/vim/vim71/syntax/verilogams.vim
#usr/share/vim/vim71/syntax/vgrindefs.vim
#usr/share/vim/vim71/syntax/vhdl.vim
#usr/share/vim/vim71/syntax/vim.vim
#usr/share/vim/vim71/syntax/viminfo.vim
#usr/share/vim/vim71/syntax/virata.vim
#usr/share/vim/vim71/syntax/vmasm.vim
#usr/share/vim/vim71/syntax/vrml.vim
#usr/share/vim/vim71/syntax/vsejcl.vim
#usr/share/vim/vim71/syntax/wdiff.vim
#usr/share/vim/vim71/syntax/web.vim
#usr/share/vim/vim71/syntax/webmacro.vim
#usr/share/vim/vim71/syntax/wget.vim
#usr/share/vim/vim71/syntax/whitespace.vim
#usr/share/vim/vim71/syntax/winbatch.vim
#usr/share/vim/vim71/syntax/wml.vim
#usr/share/vim/vim71/syntax/wsh.vim
#usr/share/vim/vim71/syntax/wsml.vim
#usr/share/vim/vim71/syntax/wvdial.vim
#usr/share/vim/vim71/syntax/xdefaults.vim
#usr/share/vim/vim71/syntax/xf86conf.vim
#usr/share/vim/vim71/syntax/xhtml.vim
#usr/share/vim/vim71/syntax/xinetd.vim
#usr/share/vim/vim71/syntax/xkb.vim
#usr/share/vim/vim71/syntax/xmath.vim
#usr/share/vim/vim71/syntax/xml.vim
#usr/share/vim/vim71/syntax/xmodmap.vim
#usr/share/vim/vim71/syntax/xpm.vim
#usr/share/vim/vim71/syntax/xpm2.vim
#usr/share/vim/vim71/syntax/xquery.vim
#usr/share/vim/vim71/syntax/xs.vim
#usr/share/vim/vim71/syntax/xsd.vim
#usr/share/vim/vim71/syntax/xslt.vim
#usr/share/vim/vim71/syntax/xxd.vim
#usr/share/vim/vim71/syntax/yacc.vim
#usr/share/vim/vim71/syntax/yaml.vim
#usr/share/vim/vim71/syntax/z8a.vim
#usr/share/vim/vim71/syntax/zsh.vim
#usr/share/vim/vim71/tools
#usr/share/vim/vim71/tools/README.txt
#usr/share/vim/vim71/tools/blink.c
#usr/share/vim/vim71/tools/ccfilter.1
#usr/share/vim/vim71/tools/ccfilter.c
#usr/share/vim/vim71/tools/ccfilter_README.txt
#usr/share/vim/vim71/tools/efm_filter.pl
#usr/share/vim/vim71/tools/efm_filter.txt
#usr/share/vim/vim71/tools/efm_perl.pl
#usr/share/vim/vim71/tools/mve.awk
#usr/share/vim/vim71/tools/mve.txt
#usr/share/vim/vim71/tools/pltags.pl
#usr/share/vim/vim71/tools/ref
#usr/share/vim/vim71/tools/shtags.1
#usr/share/vim/vim71/tools/shtags.pl
#usr/share/vim/vim71/tools/vim132
#usr/share/vim/vim71/tools/vim_vs_net.cmd
#usr/share/vim/vim71/tools/vimm
#usr/share/vim/vim71/tools/vimspell.sh
#usr/share/vim/vim71/tools/vimspell.txt
#usr/share/vim/vim71/tools/xcmdsrv_client.c
#usr/share/vim/vim71/tutor
#usr/share/vim/vim71/tutor/README.gr.cp737.txt
#usr/share/vim/vim71/tutor/README.gr.txt
#usr/share/vim/vim71/tutor/README.txt
#usr/share/vim/vim71/tutor/tutor
#usr/share/vim/vim71/tutor/tutor.ca
#usr/share/vim/vim71/tutor/tutor.cs
#usr/share/vim/vim71/tutor/tutor.cs.cp1250
#usr/share/vim/vim71/tutor/tutor.cs.utf-8
#usr/share/vim/vim71/tutor/tutor.de
#usr/share/vim/vim71/tutor/tutor.es
#usr/share/vim/vim71/tutor/tutor.fr
#usr/share/vim/vim71/tutor/tutor.gr
#usr/share/vim/vim71/tutor/tutor.gr.cp737
#usr/share/vim/vim71/tutor/tutor.gr.utf-8
#usr/share/vim/vim71/tutor/tutor.hu
#usr/share/vim/vim71/tutor/tutor.hu.utf-8
#usr/share/vim/vim71/tutor/tutor.it
#usr/share/vim/vim71/tutor/tutor.ja.euc
#usr/share/vim/vim71/tutor/tutor.ja.sjis
#usr/share/vim/vim71/tutor/tutor.ja.utf-8
#usr/share/vim/vim71/tutor/tutor.ko.euc
#usr/share/vim/vim71/tutor/tutor.ko.utf-8
#usr/share/vim/vim71/tutor/tutor.no
#usr/share/vim/vim71/tutor/tutor.pl
#usr/share/vim/vim71/tutor/tutor.pl.cp1250
#usr/share/vim/vim71/tutor/tutor.pl.utf-8
#usr/share/vim/vim71/tutor/tutor.ru
#usr/share/vim/vim71/tutor/tutor.ru.cp1251
#usr/share/vim/vim71/tutor/tutor.ru.utf-8
#usr/share/vim/vim71/tutor/tutor.sk
#usr/share/vim/vim71/tutor/tutor.sk.cp1250
#usr/share/vim/vim71/tutor/tutor.sk.utf-8
#usr/share/vim/vim71/tutor/tutor.sv
#usr/share/vim/vim71/tutor/tutor.tr.iso9
#usr/share/vim/vim71/tutor/tutor.tr.utf-8
#usr/share/vim/vim71/tutor/tutor.vim
#usr/share/vim/vim71/tutor/tutor.zh.big5
#usr/share/vim/vim71/tutor/tutor.zh.euc
#usr/share/vim/vim71/vimrc_example.vim
