#usr/include/cairo
#usr/include/cairo/cairo-deprecated.h
#usr/include/cairo/cairo-features.h
#usr/include/cairo/cairo-ft.h
#usr/include/cairo/cairo-pdf.h
#usr/include/cairo/cairo-ps.h
#usr/include/cairo/cairo-svg.h
#usr/include/cairo/cairo.h
#usr/lib/libcairo.la
usr/lib/libcairo.so
usr/lib/libcairo.so.2
usr/lib/libcairo.so.2.17.5
#usr/lib/pkgconfig/cairo-ft.pc
#usr/lib/pkgconfig/cairo-pdf.pc
#usr/lib/pkgconfig/cairo-png.pc
#usr/lib/pkgconfig/cairo-ps.pc
#usr/lib/pkgconfig/cairo-svg.pc
#usr/lib/pkgconfig/cairo.pc
#usr/share/gtk-doc/html/cairo
#usr/share/gtk-doc/html/cairo/Drawing.html
#usr/share/gtk-doc/html/cairo/Fonts.html
#usr/share/gtk-doc/html/cairo/Support.html
#usr/share/gtk-doc/html/cairo/Surfaces.html
#usr/share/gtk-doc/html/cairo/bindings-errors.html
#usr/share/gtk-doc/html/cairo/bindings-fonts.html
#usr/share/gtk-doc/html/cairo/bindings-memory.html
#usr/share/gtk-doc/html/cairo/bindings-overloading.html
#usr/share/gtk-doc/html/cairo/bindings-path.html
#usr/share/gtk-doc/html/cairo/bindings-patterns.html
#usr/share/gtk-doc/html/cairo/bindings-return-values.html
#usr/share/gtk-doc/html/cairo/bindings-streams.html
#usr/share/gtk-doc/html/cairo/bindings-surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-Error-Handling.html
#usr/share/gtk-doc/html/cairo/cairo-Font-Options.html
#usr/share/gtk-doc/html/cairo/cairo-FreeType-Fonts.html
#usr/share/gtk-doc/html/cairo/cairo-Image-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-PDF-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-PNG-Support.html
#usr/share/gtk-doc/html/cairo/cairo-Paths.html
#usr/share/gtk-doc/html/cairo/cairo-Patterns.html
#usr/share/gtk-doc/html/cairo/cairo-PostScript-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-Quartz-Fonts.html
#usr/share/gtk-doc/html/cairo/cairo-Quartz-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-SVG-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-Scaled-Fonts.html
#usr/share/gtk-doc/html/cairo/cairo-Text.html
#usr/share/gtk-doc/html/cairo/cairo-Transformations.html
#usr/share/gtk-doc/html/cairo/cairo-Types.html
#usr/share/gtk-doc/html/cairo/cairo-Version-Information.html
#usr/share/gtk-doc/html/cairo/cairo-Win32-Fonts.html
#usr/share/gtk-doc/html/cairo/cairo-Win32-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-XLib-Surfaces.html
#usr/share/gtk-doc/html/cairo/cairo-cairo-font-face-t.html
#usr/share/gtk-doc/html/cairo/cairo-cairo-matrix-t.html
#usr/share/gtk-doc/html/cairo/cairo-cairo-surface-t.html
#usr/share/gtk-doc/html/cairo/cairo-cairo-t.html
#usr/share/gtk-doc/html/cairo/cairo.devhelp
#usr/share/gtk-doc/html/cairo/cairo.devhelp2
#usr/share/gtk-doc/html/cairo/home.png
#usr/share/gtk-doc/html/cairo/index-1.2.html
#usr/share/gtk-doc/html/cairo/index-1.4.html
#usr/share/gtk-doc/html/cairo/index-1.6.html
#usr/share/gtk-doc/html/cairo/index.html
#usr/share/gtk-doc/html/cairo/index.sgml
#usr/share/gtk-doc/html/cairo/ix01.html
#usr/share/gtk-doc/html/cairo/language-bindings.html
#usr/share/gtk-doc/html/cairo/left.png
#usr/share/gtk-doc/html/cairo/right.png
#usr/share/gtk-doc/html/cairo/style.css
#usr/share/gtk-doc/html/cairo/up.png
