#bin/bashbug
#usr/share/doc/bash-3.2
#usr/share/doc/bash-3.2/bash.html
#usr/share/doc/bash-3.2/bashref.html
#usr/share/info/bash.info
#usr/share/locale/en@boldquot/LC_MESSAGES/bash.mo
#usr/share/locale/en@quot/LC_MESSAGES/bash.mo
#usr/share/locale/ru/LC_MESSAGES/bash.mo
#usr/share/man/man1/bash.1
#usr/share/man/man1/bashbug.1
