#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007, 2008  Michael Tremer & Christian Schmidt                #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

FILE=$1
GLOBAL_OPTIONS=xf

# Matches tar.gz and tgz
if grep -q gz$ <<<$FILE; then
	OPTIONS="z$GLOBAL_OPTIONS"

# Matches tar.bz2, tz2 and tbz2
elif grep -q z2$ <<<$FILE; then
	OPTIONS="j$GLOBAL_OPTIONS"

# Matches tar.lzma and tlz
elif grep -q lzma$ <<<$FILE || grep -q lz$ <<<$FILE; then
	OPTIONS="--lzma -$GLOBAL_OPTIONS"

fi

echo "Extracting $(basename $FILE)..."
exec tar $OPTIONS $FILE
