#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/bonding
#
# Description : Interface Bonding Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script collects two or more interfaces in one
#               bonding intreface.
#
########################################################################

. /lib/lsb/init-functions
. ${IFCONFIG}

case "${2}" in
	up)
		MESSAGE="Bringing up bonding interface ${1}..."
		ifenslave ${1} ${SLAVE_INTERFACES}
		evaluate_retval
	;;

	down)
		MESSAGE="Bringing down bonding interface ${1}..."
		modprobe -r bonding 2>/dev/null
		evaluate_retval
	;;

	*)
		echo "Usage: ${0} [interface] {up|down}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/bonding
