#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/bridge-slave
#
# Description : Bridge Slave Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script adds a nic to a bridge.
#
########################################################################

. /lib/lsb/init-functions
. ${IFCONFIG}

interface=${IFCONFIG##*/}

case "${2}" in
	up)
		MESSAGE="Adding slave interface ${interface} to the ${1} interface..."
		ip link set ${interface} up || failed=1
		brctl addif ${1} ${interface} || failed=1
		(exit ${failed})
		evaluate_retval
	;;

	down)
		MESSAGE="Removing slave interface ${interface} from the ${1} interface..."
		brctl delif ${1} ${interface} || failed=1
		ip link set ${interface} down || failed=1
		(exit ${failed})
		evaluate_retval
	;;

	*)
		echo "Usage: ${0} [interface] {up|down}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/bridge-slave
