#!/bin/bash

. $(dirname ${0})/qa-include

# Remove documentation files
log "Removing documentation files..."
for dir in ${BUILDROOT}/usr/{,share}/{doc,info}; do
	if [ -d "${dir}" ]; then
		log "  Removing: ${dir}"
		rm -rf ${dir} || exit $?
	fi
done

exit 0
