#!/bin/bash

. $(dirname ${0})/qa-include

# Check for absolute symlinks.
# We do not allow them because they may point to any bad location.

log_debug "Search for absolute symlinks"

failed=0
for link in $(find ${BUILDROOT} -type l); do
	if fgrep -q "/lib/udev/devices" <<<${link}; then
		continue
	fi

	destination=$(readlink ${link})
	if [ "${destination:0:1}" = "/" ]; then
		log_error "  absolute symlink: ${link}"
		failed=1
	fi
	if [ ! -e "${link%/*}/${destination}" ]; then
		log_error "  not existant destination: ${link} -> ${destination}"
		failed=1
	fi
done

exit ${failed}
