#!/bin/bash

. $(dirname ${0})/qa-include

# Check for libs that are missing in /usr/lib.

log_debug "Checking correct installation of libraries"

failed=0
for lib in $(find ${BUILDROOT}/lib -type f -name "lib*.so.*" 2>/dev/null); do
	lib=${lib##*/}
	lib=${lib%%.so*}

	if [ ! -e "${BUILDROOT}/usr/lib/${lib}.so" ]; then
		failed=1
		log_error "  /usr/lib/${lib}.so is missing"
	fi
done

exit ${failed}
