#!/bin/bash

. $(dirname ${0})/qa-include

DESC="Text relocations force the dynamic linker to perform extra \
	work at startup, waste system resources, and may pose a security \
	risk. On some architectures, the code may not even function \
	properly, if at all."

function check() {
	local failed=0

	local file
	for file in $(find_elf_files --prefix=${BUILDROOT} ${BINARY_PATHS}); do
		if filter_startfiles ${file}; then
			continue
		fi

		if ! file_is_relro_full ${file}; then
			log_error "  Is not full relro: ${file}"
			failed=1
		fi
	done

	return ${failed}
}

run
