#!/bin/bash

. $(dirname ${0})/qa-include

function check() {
	local failed=0

	local file
	for file in $(find_elf_files ${BINARY_PATHS}); do
		if ! has_nx ${file}; then
			log_error "  No NX: ${file}"
			failed=1
		fi
	done

	return ${failed}
}

run
