#!/bin/bash

. $(dirname ${0})/qa-include

DESC="Every binary file has to provide a canary."

function check() {
	local failed=0

	local file
	for file in $(find_elf_files ${BINARY_PATHS}); do
		if filter_startfiles ${file}; then
			continue
		fi

		if ! has_canary ${file}; then
			log_error "  Has no canary: ${file}"
			failed=1
		fi
	done

	return ${failed}
}

run
