#!/bin/bash

. $(dirname ${0})/qa-include

DESC="Searching for RPATHs. We don't want paths that point to the tree where \
	the package was built (older, broken libtools would do this). \
	Also check for null paths because the loader will search \$PWD when it \
	finds null paths."

check() {
	for i in $QUALITY_AGENT_WHITELIST_RPATH; do
		if [ -n "$FILTER" ]; then
			FILTER="$FILTER|$i"
		else
			FILTER="$i"
		fi
	done
	
	if [ -n "$FILTER" ]; then
		log_debug "  Filter: $FILTER"
	fi

	local failed=0

	local file
	local rpath
	for file in $(find_elf_files ${BINARY_PATHS}); do
		if filtered ${file}; then
			continue
		fi

		rpath=$(get_rpath ${file})
		if [ -n "${rpath}" ]; then
			log_error "  File has rpath: ${file} - ${rpath}"
			failed=1
		fi
	done

	return ${failed}
}

run
