#!/bin/bash

. $(dirname ${0})/qa-include

log "Check for binaries in /bin or /sbin that link to /usr/..."

for file in $(find ${BUILDROOT}/{bin,lib,sbin}/* 2>/dev/null); do
	[ -f "${file}" ] || continue
	log "  ${file}"

	interpreter=$(get_interpreter ${file})
	if [ ! -e "${interpreter}" ]; then
		log "  SKIPPED because interpreter is not available"
		continue
	fi

	libs=$(ldd ${file})
	if grep -q /usr/lib <<<${libs}; then
		log "ERROR: ${file} links to libs in /usr/lib..."
		log "  ${libs}"
		exit 1
	fi
done

exit 0
