#!/bin/bash

. $(dirname ${0})/qa-include

# TEXTREL's are baaaaaaaad
log "Searching for bad TEXTRELs"

files=$(scanelf -qyRF '%t %p' ${BUILDROOT} 2>/dev/null | awk '{ print $NF }')
if [ -n "${files}" ]; then
	log "  QA Notice: The following files contain runtime text relocations"
	log "   Text relocations force the dynamic linker to perform extra"
	log "   work at startup, waste system resources, and may pose a security"
	log "   risk. On some architectures, the code may not even function"
	log "   properly, if at all."
	log "${files}"

	exit 1
fi

exit 0
