#!/bin/bash

function log() {
	printf "%-22s: %s\n" "${0##*/}" "$@"
}

if [ -z "${BUILDROOT}" ]; then
	echo "${0##*/}: ERROR: BUILDROOT is not set." >&2
	exit 1
fi

# Include additional functions
. $(dirname ${0})/qa-functions
