#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2009  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

[ -f "/etc/sysconfig/network" ] && . /etc/sysconfig/network

function is_mac() {
	egrep "^[0-9a-f][0-9a-f]\:[0-9a-f][0-9a-f]\:[0-9a-f][0-9a-f]\:[0-9a-f][0-9a-f]\:[0-9a-f][0-9a-f]\:[0-9a-f][0-9a-f]$" <<<$1
}

function get_device_by_mac() {
	local mac=$1
	for i in /sys/class/net/*; do
		if [ "$(cat $i/address)" = "$mac" ]; then
			echo $(basename $i)
		fi
	done
}

function get_mac_by_device() {
	local device=$1
	if [ -d "/sys/class/net/$device" ]; then
		cat /sys/class/net/$device/address
		return 0
	fi
	return 1
}

function device_exists() {
	ip link show ${1} &>/dev/null
}

function zone_exists() {
	[ -e "$CONFIG_ZONES/$1" ] #|| device_exists $@
}

function bridge_devices() {
	: #TODO
}
