#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007, 2008, 2009 Michael Tremer & Christian Schmidt           #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

if [ "$INTERFACE" = "" ]; then
	exit 1
fi

case $ACTION in
	add|register)
		case $INTERFACE in
			# interfaces that are brought up as a part of configuration
			ppp*|ippp*|isdn*|plip*|lo*|irda*|dummy*|ipsec*|tun*|tap*)
				exit 0
				;;
			# interfaces that are registered then brought up
			*)
				export IN_HOTPLUG=1
				## Put ifup code here
				;;
		esac
		;;

	remove|unregister)
		case $INTERFACE in
			# interfaces that are brought down as part of deconfiguration
			ppp*|ippp*|isdn*|plip*|lo*|irda*|dummy*|ipsec*|tun*|tap*)
				exit 0
				;;
			*)
				export IN_HOTPLUG=1
				## Put ifdown code here
				;;
		esac
		;;

	*)
		exit 1
		;;

esac
