#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2009  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /lib/lsb/init-functions
. /etc/init.d/networking/functions

zone=$1
action=$2

if [ -z "${zone}" ] || [ -z "${action}" ]; then
	echo "Usage: $0 <zone> <up|down>"
	echo
	exit 1
fi

if ! zone_exists ${zone}; then
	echo "Zone ${zone} does not exist."
	exit 1
fi

case "$action" in
	up)
		message="Bringing up zone ${zone}..."

		run_hooks pre-up ${CONFIG_ZONES}/${zone} ${zone}

		# Check if bridge already exists
		zone_status=`brctl show 2>/dev/null`
		if ! echo "${zone_status}" | grep -q "^${zone}"; then
			# Create and bring up the zone
			brctl addbr ${zone} || failed=1
			ip link set ${zone} up || failed=1
			(exit ${failed})
			evaluate_retval standard
		fi

		# Attach ports
		for config in $(find ${CONFIG_ZONES}/${zone}/ -name "port-*" 2>/dev/null); do
			port=${config##*/}; port=${port#port-}; port=${port%%-*}
			ZONE=${zone} /etc/init.d/networking/port ${port} attach ${config}
		done

		run_hooks post-up ${CONFIG_ZONES}/${zone} ${zone}
		;;

	down)
		message="Bringing down zone ${zone}..."
		# Check if bridge already exists
		zone_status=`brctl show 2>/dev/null`
		if echo "${zone_status}" | grep -q "^${zone}"; then
			run_hooks pre-down ${CONFIG_ZONES}/${zone} ${zone}

			# Detach ports
			for config in $(find ${CONFIG_ZONES}/${zone}/ -name "port-*" 2>/dev/null); do
				port=${config##*/}; port=${port#port-}; port=${port%%-*}
				ZONE=${zone} /etc/init.d/networking/port ${port} detach ${config}
			done

			# Bring down the zone and delete it
			ip link set ${zone} down || failed=1
			brctl delbr ${zone} || failed=1
			(exit ${failed})
			evaluate_retval standard

			run_hooks post-down ${CONFIG_ZONES}/${zone} ${zone}
		else
			log_warning_msg ${message}
			log_warning_msg "Zone ${zone} does not exist."
		fi
		;;
esac
