#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007, 2008, 2009 Michael Tremer & Christian Schmidt           #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

EXIT_CODE=0

echo "  Searching for world-writeable files..."

f=$(find ${1} -type f -perm -2 2>/dev/null)
if [ -n "$f" ]; then
	echo "  QA Security Notice:"
	echo "   - The folloing files will be world writable."
	echo "   - This may or may not be a security problem, most of the time it is one."
	echo "   - Please double check that these files really need a world writeable bit and file bugs accordingly."
	echo
	echo "$f"
	EXIT_CODE=1
fi

f=$(find ${1} -type f '(' -perm -2002 -o -perm -4002 ')')
if [ -n "$f" ]; then
	echo "  QA Notice: Unsafe files detected (set*id and world writable)"
	echo
	echo "$f"
	EXIT_CODE=1
fi

exit $EXIT_CODE
