#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007, 2008, 2009 Michael Tremer & Christian Schmidt           #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

TMP_DIR=$1

check_files=$(find ${TMP_DIR} -name lib*.so*)

echo "  Searching bad libs that lack the NEEDED attribute..."
if [ -n "$check_files" ]; then
	f=$(scanelf -ByF '%n %p' $check_files | awk '$2 == "" { print }')
	if [ -n "$f" ]; then
		echo "  QA Notice: The following shared libraries lack NEEDED entries"
		echo "${f}"
		exit 1
	fi
fi
