usr/bin/gdb
usr/bin/gdbserver
usr/bin/gdbtui
#usr/lib/libbfd.a
#usr/lib/libopcodes.a
#usr/share/info/annotate.info
#usr/share/info/gdb.info
#usr/share/info/gdb.info-1
#usr/share/info/gdb.info-2
#usr/share/info/gdb.info-3
#usr/share/info/gdb.info-4
#usr/share/info/gdbint.info
#usr/share/info/gdbint.info-1
#usr/share/info/gdbint.info-2
#usr/share/info/stabs.info
#usr/share/man/man1/gdb.1
#usr/share/man/man1/gdbserver.1
#usr/share/man/man1/gdbtui.1
