#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2012  IPFire Network Development Team                         #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /usr/lib/network/functions

# Read network settings
network_settings_read

device="${1}"
assert isset device

# Create socket dir.
mkdir -p ${WPA_SUPPLICANT_SOCKET_DIR} 2>/dev/null

cmd="wpa_supplicant -i ${device} -c ${WPA_SUPPLICANT_CONF_DIR}/${device}.conf"

if device_is_wireless ${device}; then
	cmd="${cmd} -Dnl80211"
else
	cmd="${cmd} -Dwired"
fi

cmd_exec ${cmd}
