#!/bin/sh

. /etc/init/functions
. /lib/network/functions

INDENT=" "

HOOK_PRIO=100

# Parse the command line
action=
port=
zone=

while [ $# -gt 0 ]; do
	case "${1}" in
		--zone=*)
			zone=${1#--zone=}
			;;
		--config=*)
			. ${1#--config=}
			;;
		--port=*)
			port=${1#--port=}
			;;
		-*)
			log_failure_msg "Unrecognized option: ${1}"
			exit ${EXIT_ERROR}
			;;
		*)
			action=${1}
			shift
			break
			;;
	esac
	shift
done

