#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2010  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

. /usr/lib/network/header-port

HOOK_SETTINGS="HOOK DEVICE_MAC"

function _check() {
	assert ismac DEVICE_MAC
}

function _create() {
	local port=${1}
	shift

	assert isset port

	DEVICE_MAC=$(device_get_address ${port})

	config_write $(port_file ${port}) ${HOOK_SETTINGS}

	exit ${EXIT_OK}
}

function _up() {
	local port=${1}

	assert isset port

	device_set_up ${port}

	exit ${EXIT_OK}
}

function _down() {
	local port=${1}

	assert isset port

	device_set_down ${port}

	exit ${EXIT_OK}
}

function _hotplug_rename() {
	local port=${1}
	local device=${2}

	assert isset port
	assert isset device

	config_read $(port_file ${port})

	if [ "${DEVICE_MAC}" = "$(device_get_address ${device})" ]; then
		log DEBUG "Device '${device}' equals port '${port}'."
		exit ${EXIT_OK}
	fi

	log DEBUG "Device '${device}' does not equal port '${port}'."
	exit ${EXIT_ERROR}
}
