#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/stp
#
# Description : Spanning Tree Protocol Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script adds stp support to a bridge.
#
########################################################################

. /lib/lsb/init-functions
. /lib/network/functions

[ -n "${CONFIG}" ] && . ${CONFIG}

zone=$2

case "${1}" in
	pre-up)
		;;

	post-up)
		MESSAGE="Enabling Spanning Tree Protocol on zone ${zone}..."
		brctl stp ${zone} on
		evaluate_retval
		;;

	pre-down)
		MESSAGE="Disabling Spanning Tree Protocol on zone ${zone}..."
		brctl stp ${zone} off
		evaluate_retval
		;;

	post-down)
		;;

	config)
		: # TODO
		;;

	*)
		echo "Usage: ${0} {pre-up|post-up|pre-down|post-down|config} [interface]"
		exit 1
		;;
esac

# End $NETWORK_DEVICES/services/stp
