#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/vlan
#
# Description : VLAN Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script adds vlan support.
#
########################################################################

. /lib/lsb/init-functions
. /lib/network/functions

[ -n "${CONFIG}" ] && . ${CONFIG}

port=$(macify ${1})
device=$(devicify ${port})

function port_name() {
	echo "${ZONE}v${ID}"
}

function do_up() {
	if ! port_is_up $(port_name); then
		grep -q ^8021q /proc/modules || modprobe 8021q
		MESSAGE="Adding VLAN ${ID} to port ${port}..."
		vconfig add ${device} ${ID} >/dev/null
		evaluate_retval
	fi
}

function do_down() {
	if port_is_up $(port_name); then
		MESSAGE="Removing VLAN ${ID} from port ${port}..."
		vconfig rem ${device} ${ID} >/dev/null
		evaluate_retval
	fi
}

function do_attach() {
	rename_device $(get_device_by_mac_and_vid ${port} ${ID}) $(port_name)
	zone_add_port ${ZONE} $(get_device ${port} ${ID})
}

function do_detach() {
	zone_del_port ${ZONE} $(get_device_by_mac_and_vid ${port} ${ID})
}

function do_status() {
	device_is_up $(port_name)
	RET=$?
	if [ $RET -eq 0 ]; then
		log_success_msg "Port $(port_name) is up"
	else
		log_failure_msg "Port $(port_name) is down"
	fi
	return $RET
}

case "${2}" in
	up)
		do_up
	;;

	down)
		do_down
	;;

	add)
		ID=$3
		cat <<EOF > ${CONFIG_PORTS}/${port}/vlan-${ID}
HOOK=vlan
ID=${ID}
EOF
		ln -sf ${CONFIG_PORTS}/${port}/vlan-${ID} \
			${CONFIG_ZONES}/${ZONE}/port-${port}-vlan-${ID}
	;;

	remove)
		do_detach
		do_down
		rm -f \
			${CONFIG_PORTS}/${port}/vlan-${ID} \
			${CONFIG_ZONES}/${ZONE}/port-${port}-vlan-${ID}
	;;

	attach)
		do_attach
	;;
	
	detach)
		do_detach
	;;

	status)
		do_status
		exit ${?}
	;;

	*)
		echo "Usage: ${0} [interface] {up|down|add|remove|attach|detach|status}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/vlan
