#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2008, 2009  Michael Tremer & Christian Schmidt                #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

[[ $# -eq 1 ]] || { echo "Usage: $(basename $0) <initrd file>" ; exit 1 ; }
[[ -f $1 ]]    || { echo "$1 does not exist" ; exit 1 ; }
 
echo "$1:"
echo "========================================================================"
zcat $1 | cpio --extract --verbose --quiet --list
echo "========================================================================"
zcat $1 | cpio --extract --verbose --quiet --to-stdout init
echo "========================================================================"
zcat $1 | cpio --extract --verbose --quiet --to-stdout sbin/real-init
echo "========================================================================"
