#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/bridge-slave
#
# Description : Bridge Slave Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script adds a nic to a bridge.
#
########################################################################

. /lib/lsb/init-functions
. ${IFCONFIG}

interface=${IFCONFIG##*/}

. /etc/init.d/networking/functions

case "${2}" in
	up)
		if ! device_exists ${BRIDGE}; then
			MESSAGE="Bringing up bridge ${BRIDGE}..."
			brctl addbr ${BRIDGE} || failed=1
			ip link set ${BRIDGE} up || failed=1
			(exit ${failed})
			evaluate_retval
		fi

		MESSAGE="Adding slave interface ${interface} to the ${1} interface..."
		brctl addif ${1} ${interface}
		evaluate_retval
	;;

	down)
		MESSAGE="Removing slave interface ${interface} from the ${1} interface..."
		brctl delif ${1} ${interface}
		evaluate_retval
	;;

	*)
		echo "Usage: ${0} [interface] {up|down}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/bridge-slave
