#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/ethernet
#
# Description : Ethernet Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script adds ethernet support.
#
########################################################################

. /lib/lsb/init-functions
. /etc/init.d/networking/functions
[ -n "${CONFIG}" ] && . ${CONFIG}

port=$(macify ${1})

case "${2}" in
	up)
		: # Do nothing
	;;

	down)
		: # Do nothing
	;;

	add)
		cat <<EOF > ${CONFIG_PORTS}/${port}/ethernet
HOOK=ethernet
EOF
		ln -sf ${CONFIG_PORTS}/${port}/ethernet \
			${CONFIG_ZONES}/${ZONE}/port-${port}-ethernet
	;;

	remove)
		rm -f \
			${CONFIG_ZONES}/${ZONE}/port-${port}-ethernet \
			${CONFIG_PORTS}/${port}/ethernet
	;;

	attach)
		zone_add_port ${ZONE} $(get_device ${port})
	;;

	detach)
		zone_del_port ${ZONE} $(get_device ${port})
	;;

	*)
		echo "Usage: ${0} [interface] {up|down|add|remove|attach|detach}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/ethernet
