#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/mtu
#
# Description : Sets MTU per interface
#
# Authors     : Nathan Coulson - nathan@linuxfromscratch.org
#               Jim Gifford - jim@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       : This sets the maximum amount of bytes that can be
#               transmitted within a packet. By default, this
#               value is set to 1500.
#
########################################################################

. /lib/lsb/init-functions
[ -n "${CONFIG}" ] && . ${CONFIG}

zone=$1

if [ -z "${MTU}" ]
then
	log_failure_msg "MTU variable missing from ${CONFIG}, cannot continue."
	exit 1
fi

case "${2}" in
	up)
		message="Setting the MTU for ${zone} to ${MTU}..."
		echo "${MTU}" > "/sys/class/net/${zone}/mtu"
		evaluate_retval standard
	;;

	down)
	;;

	*)
		echo "Usage: ${0} [interface] {up|down}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/mtu
