#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/mtu
#
# Description : Sets MTU per interface
#
# Authors     : Nathan Coulson - nathan@linuxfromscratch.org
#               Jim Gifford - jim@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       : This sets the maximum amount of bytes that can be
#               transmitted within a packet. By default, this
#               value is set to 1500.
#
########################################################################

. /lib/lsb/init-functions
. /etc/init.d/networking/functions
[ -n "${CONFIG}" ] && . ${CONFIG}

function check_config() {
	if [ -z "${MTU}" ]; then
		log_failure_msg "MTU variable missing from ${CONFIG}, cannot continue."
		exit 1
	fi
	if [ -z "${zone}" ]; then
		usage
		exit 1
	fi
}

function usage() {
	echo "Usage: ${0} {pre-up|post-up|pre-down|post-down|config} [interface]"
}

zone=$2

case "${1}" in
	pre-up)
		;;

	post-up)
		check_config
		message="Setting the MTU for ${zone} to ${MTU}..."
		echo "${MTU}" > "/sys/class/net/${zone}/mtu"
		evaluate_retval standard
		;;

	pre-down)
		check_config
		message="Resetting MTU for ${zone} to 1500..."
		echo "1500" > "/sys/class/net/${zone}/mtu"
		evaluate_retval standard
		;;

	post-down)
		;;

	config)
		;;

	*)
		usage
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/mtu
