#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/stp
#
# Description : Spanning Tree Protocol Script
#
# Authors     : Michael Tremer - michael.tremer@ipfire.org
#
# Version     : 00.00
#
# Notes       : This script adds stp support to a bridge.
#
########################################################################

. /lib/lsb/init-functions
[ -n "${CONFIG}" ] && . ${CONFIG}

case "${2}" in
	up)
		MESSAGE="Enabling Spanning Tree Protocol on interface ${1}..."
		brctl stp ${1} on
		evaluate_retval
	;;

	down)
		MESSAGE="Disabling Spanning Tree Protocol on interface ${1}..."
		brctl stp ${1} off
		evaluate_retval
	;;

	*)
		echo "Usage: ${0} [interface] {up|down}"
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/stp
