#!/bin/sh
# Begin /etc/init.d/fcron

### BEGIN INIT INFO
# Provides:            fcron
# Required-Start:      $syslog
# Should-Start:
# Required-Stop:       $syslog
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts fcron.
# Description:         Starts the fcron daemon.
# X-LFS-Default-Start: S40
# X-LFS-Default-Stop:  K08
# X-LFS-Provided-By:
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="F-Cron Daemon"
BIN_FILE="/usr/sbin/fcron"
PIDFILE="/var/run/fcron.pid"

chk_stat

case "$1" in
    start)
        start_daemon -p "${PIDFILE}" "${BIN_FILE}"
        evaluate_retval start
        ;;

    stop)
        killproc -p "${PIDFILE}" "${BIN_FILE}"
        evaluate_retval stop
        ;;

    restart)
        killproc -p "${PIDFILE}" "$BIN_FILE" 
        sleep 1
        start_daemon -p "${PIDFILE}" "${BIN_FILE}"
        evaluate_retval restart
        ;;

    status)
        statusproc -p "${PIDFILE}" "${BIN_FILE}"
        ;;

    *)
        echo "Usage: $0 {start|stop|restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/fcron
