#!/bin/sh
# Begin /etc/init.d/firewall

### BEGIN INIT INFO
# Provides:            firewall
# Required-Start:      $network
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   IPFire Firewall Engine.
# Description:         This controls the IPFire Firewall Engine.
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="IPFire Firewall"
BIN_FILE="/usr/bin/firewall"

chk_stat

case "$1" in
    start)
        ${BIN_FILE} start
        evaluate_retval start
        touch /var/lock/subsys/firewall
    ;;

    stop)
        ${BIN_FILE} stop
        evaluate_retval stop
        rm -f /var/lock/subsys/firewall
    ;;

    restart)
		${BIN_FILE} restart
		evaluate_retval restart
    ;;
    
    reload)
		${BIN_FILE} reload
		evaluate_retval reload
    ;;

    *)
        echo "    Usage:  ${0}{start|stop|restart|reload}"
        if [ "${1}" = "status" -o "${1}" = "try-restart" ]
        then
            echo "    Error:  Unimplemented function '${1}'"
            exit 3
        else
            exit 2
        fi
    ;;

esac

# End /etc/init.d/firewall
