#!/bin/sh
# Begin /etc/init.d/lighttpd

### BEGIN INIT INFO
# Provides:            lighttpd
# Required-Start:      $network
# Should-Start:
# Required-Stop:
# Should-Stop:         netfs
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts the lighttpd daemon.
# Description:         Starts the lighttpd daemon
#	which is the system's webserver.
# X-LFS-Default-Start:
# X-LFS-Default-Stop:
# X-LFS-Provided-By:
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="Lighttpd Daemon"
BIN_FILE="/usr/sbin/lighttpd"
CONFIGFILE="/etc/lighttpd.conf"

chk_stat

case "${1}" in
    start)
        loadproc -f $CONFIGFILE
        evaluate_retval start
        ;;

    stop)
        endproc
        evaluate_retval stop
        ;;

    force-reload)
        reloadproc -force
        evaluate_retval force-reload
        ;;

    restart)
        $0 stop
        $0 start
        ;;

    status)
        statusproc
        ;;

    reload)
        reloadproc
        evaluate_retval reload
        ;;

    *)
        echo "Usage: ${0} {start|stop|{force-}reload|restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/lighttpd
