#!/bin/sh
# Begin /etc/init.d/messagebus

### BEGIN INIT INFO
# Provides:            messagebus
# Required-Start:      $syslog
# Should-Start:
# Required-Stop:       $syslog
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        1
# Short-Description:   Messagebus Daemon.
# Description:         Starts the dbus messagebus daemon.
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="D-Bus Messagebus Daemon"
BIN_FILE="/usr/bin/dbus-daemon"

pidfile=/var/run/dbus/pid
socket=/var/run/dbus/system_bus_socket

chk_stat

case "${1}" in
    start)
        /usr/bin/dbus-uuidgen --ensure
        start_daemon -p ${pidfile} "${BIN_FILE}" --system
        evaluate_retval start
        ;;

    stop)
        killproc -p ${pidfile} "${BIN_FILE}"
        evaluate_retval stop
        rm -f "$socket" 2>/dev/null
        ;;

    force-reload)
        reloadproc -force
        evaluate_retval force-reload
        ;;

    restart)
        $0 stop
        $0 start
        ;;

    status)
        statusproc -p ${pidfile}
        ;;

    reload)
        reloadproc
        evaluate_retval reload
        ;;

    try-restart)
        pidofproc "${BIN_FILE}" > /dev/null
        if [ "${?}" -ne "0" ]; then
            MESSAGE="${MESSAGE}: Not Running"
        else
            $0 stop
            $0 start
            exit 0
        fi
        evaluate_retval try-restart
        ;;

    *)
        echo "Usage: ${0} {start|stop|{force-}reload|{try-}restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/messagebus
