#!/bin/sh
# Begin /etc/init.d/messagebus

### BEGIN INIT INFO
# Provides:            messagebus
# Required-Start:      $syslog
# Should-Start:
# Required-Stop:       $syslog
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Messagebus Daemon.
# Description:         Starts the dbus messagebus daemon.
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="the D-Bus Messagebus Daemon"
BIN_FILE="/usr/bin/dbus-daemon"

CONFIGFILE=/etc/dbus-1/system.conf
PIDFILE=/var/run/dbus/pid
SOCKET=/var/run/dbus/system_bus_socket

chk_stat

case "${1}" in
    start)
        /usr/bin/dbus-uuidgen --ensure >/dev/null
        start_daemon -p ${PIDFILE} "${BIN_FILE}" --config-file="${CONFIGFILE}"
        evaluate_retval start
        ;;

    stop)
        killproc -p ${PIDFILE} "${BIN_FILE}"
        evaluate_retval stop
        rm -f "${SOCKET}" "${PIDFILE}"
        ;;

    restart|force-reload)
        $0 stop
        sleep 1
        $0 start
        ;;

    status)
        statusproc -p ${PIDFILE}
        ;;

    *)
        echo "Usage: ${0} {start|stop|force-reload|restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/messagebus
