#!/bin/sh
# Begin /etc/init.d/network

### BEGIN INIT INFO
# Provides:            $network
# Required-Start:      $local_fs swap localnet
# Should-Start:        $syslog
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts and configures network interfaces.
# Description:         Starts and configures network interfaces.
# X-LFS-Default-Start: S20
# X-LFS-Default-Stop:  K80
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions
. /etc/sysconfig/network

case "${1}" in
	start)
		# Start all network interfaces
		for file in ${NETWORK_DEVICES}/*
		do
			interface=$(basename ${file})

			IN_BOOT=1 ${NETWORK_DEVICES}/brup ${interface}
		done
		;;

	stop)
		# Reverse list
		FILES=""
		for file in ${NETWORK_DEVICES}/*
		do
			FILES="${file} ${FILES}"
		done

		# Stop all network interfaces
		for file in ${FILES}
		do
			interface=$(basename ${file})

			IN_BOOT=1 ${NETWORK_DEVICES}/brdown ${interface}
		done
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	*)
		echo "Usage: ${0} {start|stop|restart}"
		exit 1
		;;
esac

# End /etc/init.d/network
