#!/bin/sh
# Begin /etc/init.d/network

### BEGIN INIT INFO
# Provides:            $network
# Required-Start:      $local_fs swap localnet
# Should-Start:        $syslog
# Required-Stop:       $local_fs swap localnet
# Should-Stop:         $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts and configures network interfaces.
# Description:         Starts and configures network interfaces.
# X-LFS-Default-Start: S20
# X-LFS-Default-Stop:  K80
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions
. /etc/init.d/networking/functions

case "${1}" in
	start)
		# Start all network interfaces
		for zone in $(find ${CONFIG_ZONES}/ -maxdepth 1); do
			[ -d "${zone}" ] || continue
			IN_BOOT=1 /etc/init.d/networking/zone ${zone##*/} up
		done
		touch /var/lock/subsys/network
		;;

	stop)
		# Stop all network interfaces
		for zone in $(find ${CONFIG_ZONES}/ -maxdepth 1); do
			[ -d "${zone}" ] || continue
			IN_BOOT=1 /etc/init.d/networking/zone ${zone##*/} down
		done
		rm -f /var/lock/subsys/network
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	*)
		echo "Usage: ${0} {start|stop|restart}"
		exit 1
		;;
esac

# End /etc/init.d/network
