#!/bin/sh
# Begin /etc/init.d/sysctl

### BEGIN INIT INFO
# Provides:            sysctl
# Required-Start:      mountkernfs
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:
# Short-Description:   Makes changes to the proc filesystem
# Description:         Makes changes to the proc filesystem as defined in
#                      /etc/sysctl.conf.  See 'man sysctl(8)'.
# X-LFS-Default-Start: S05
# X-LFS-Default-Stop:
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        if [ -f "/etc/sysctl.conf" ]; then
            message="Setting kernel runtime parameters..."
            sysctl -q -p
            evaluate_retval standard
        fi
        if [ -d "/proc/sys/kernel/grsecurity" -a \
             -f "/etc/grsec/sysctl.conf" ]; then
            message="Setting grsecurity parameters..."
            sysctl -q -p /etc/grsec/sysctl.conf
            evaluate_retval standard
        fi
        ;;

    status)
        sysctl -a    
        ;;

    *)
        echo "Usage: ${0} {start|status}"
        exit 1
        ;;
esac

# End /etc/init.d/sysctl
