#!/bin/sh
# Begin /etc/init.d/syslog-ng

### BEGIN INIT INFO
# Provides:            $syslog
# Required-Start:      localnet
# Should-Start:
# Required-Stop:       $local_fs sendsignals
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts the system log daemon.
# Description:         Starts the system log daemon.
# X-LFS-Default-Start: S10
# X-LFS-Default-Stop:  K90
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

MESSAGE="System Log Daemon"
BIN_FILE="/sbin/syslog-ng"

case "${1}" in
    start)
        loadproc
        evaluate_retval start
        ;;

    stop)
        endproc
        evaluate_retval stop
        ;;

    force-reload)
        reloadproc -force
        evaluate_retval force-reload
        ;;

    restart)
        $0 stop
        $0 start
        ;;

    status)
        statusproc
        ;;

    *)
        echo "Usage: ${0} {start|stop|force-reload|restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/syslog-ng
