#!/bin/sh
# Begin /etc/init.d/syslog-ng

### BEGIN INIT INFO
# Provides:            syslog-ng
# Required-Start:      localnet
# Should-Start:
# Required-Stop:       $local_fs sendsignals
# Should-Stop:
# Default-Start:       2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:   Starts log daemon.
# Description:         Starts log daemon.
# X-LFS-Default-Start: S10
# X-LFS-Default-Stop:  K90
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /lib/lsb/init-functions

case "${1}" in
    start)
        MESSAGE="Log daemon..."
        start_daemon /usr/local/sbin/syslog-ng
        evaluate_retval start

    stop)
        MESSAGE="Log daemon..."
        killproc /usr/local/sbin/syslog-ng
        evaluate_retval stop
        ;;

    force-reload)
        MESSAGE="Log daemon config file..."
        killproc -HUP `/usr/local/sbin/syslog-ng`
        evaluate_retval reload
        ;;

    restart)
        MESSAGE="Log deamons..."
        failed=0
        killproc /usr/local/sbin/syslog-ng || failed=1
        start_daemon /usr/local/sbin/syslog-ng || failed=1
        (exit ${failed})
        evaluate_retval restart
        ;;

    status)
        statusproc /usr/local/sbin/syslog-ng
        ;;

    *)
        echo "Usage: ${0} {start|stop|force-reload|restart|status}"
        exit 1
        ;;
esac

# End /etc/init.d/sysklog-ng
