#!/usr/bin/python
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2008  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################
#                                                                             #
# This is a very simple script for downloading our files from the server.     #
# It is keep that simple because we plan to rewrite this anytime or move      #
# away from wget.                                                             #
#                                                                             #
###############################################################################

import os
import sys
import string

from urlgrabber.grabber import URLGrabber, URLGrabError

###############################################################################
# Environment                                                                 #
###############################################################################

data = None
UUID = None
URL = "http://build.ipfire.org/build.py"

try:
	UUID = os.environ["UUID"]
except KeyError:
	sys.stderr.write("UUID isn't set.\n")
	sys.exit(1)

data = "uuid=%s" % (UUID,)

action = sys.argv[1]

data += "&action=%s" % (action,)

if action == "set":
	key = sys.argv[2]
	val = ""
	for i in sys.argv[3:]:
		if len(val):
			val += " "
		val += i
	data += "&key=%s&val=%s" % (key, val)

elif action == "error":
	LOGFILE = os.environ["LOGFILE"]
	f = open(LOGFILE)
	log = f.readlines()[-10:]
	f.close()
	data += "&log=%s" % (log,)

g = URLGrabber(user_agent = "IPFireBuildSpy/3.x",)
try:
	gobj = g.urlread(URL, data=data)
except URLGrabError, e:
	sys.stderr.write("%s: %s\n" % (__name__, e,))
	sys.exit(1)

sys.exit(0)
