#!/bin/bash

if [ -z "${BASEDIR}" ]; then
	echo "${0##*/}: ERROR: BASEDIR is not set." >&2
	exit 1
fi

. ${BASEDIR}/tools/common-constants
. ${BASEDIR}/tools/common-package-functions
. ${BASEDIR}/tools/common-ui-functions

# Read in .config
if [ -e "${BASEDIR}/.config" ]; then
	log DEBUG "Loading .config..."
	source ${BASEDIR}/.config
fi
