#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################
#                                                                             #
# This is a very simple script for downloading our files from the server.     #
# It is keep that simple because we plan to rewrite this anytime or move      #
# away from wget.                                                             #
#                                                                             #
###############################################################################

# BASEDIR, DIR_TMP, DIR_DL are given by the environment
URL="$1"
FILE="$(basename $2)"

MAX=2
COUNTER=0

WGET_OPTS="-c"

while [ "${COUNTER}" -lt "${MAX}" ]; do
	cd ${DIR_TMP}
	if wget ${WGET_OPTS} ${URL}/${FILE}{,.md5}; then
		if [ `awk '{ print $1 }' ${DIR_TMP}/${FILE}.md5` = \
				`md5sum ${DIR_TMP}/${FILE} | awk '{ print $1 }'` ]; then
			mv ${DIR_TMP}/${FILE} ${DIR_TMP}/${FILE}.md5 ${DIR_DL}
			exit 0
		else
			rm -f ${FILE}* 2>/dev/null
		fi
	else
		rm -f ${FILE}* 2>/dev/null
		exit 1
	fi
	COUNTER=${COUNTER} + 1
done

if [ "${COUNTER}" -eq "${MAX}" ]; then
	echo "Download failed." 1>&2
	exit 1
fi
