#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2008  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################
#                                                                             #
# This is a very simple script for downloading our files from the server.     #
# It is keep that simple because we plan to rewrite this anytime or move      #
# away from wget.                                                             #
#                                                                             #
###############################################################################

URL="http://source.ipfire.org/source-3.x"

objects=

while [ $# -gt 0 ]; do
	case "${1}" in
		--tarballs=*)
			DIR_TARBALLS=${1#--tarballs=}
			;;
		--patches=*)
			DIR_PATCHES=${1#--patches=}
			;;
		*)
			objects="${objects} ${1}"
			;;
	esac
	shift
done

for object in ${objects}; do
	echo object: $object
	target=
	if [[ ${object} =~ .patch$ ]]; then
		target="${DIR_PATCHES}/${object}"
	else
		target="${DIR_TARBALLS}/${object}"
	fi

	wget ${URL}/${object} -O ${target}
done
