#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2008  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

BATCHLOG=$BASEDIR/log_${MACHINE}/_build.00-batch.log

###############################################################################                   
# Starts the batch process in the background                                  #
###############################################################################
batch_start() {
	if [ -e "$RUNNING" ]; then
		echo -n "Build is already running..."
		beautify message FAIL
		exit 1
	fi

	git_pull --batch

	if [ -e "$FAILED" ]; then
		echo -n "Last build failed..."
		beautify message FAIL
		exit 1
	fi

	[ "$1" = "--clean" ] && $0 clean

	screen -dmS ipfire $0 batch _run
}

###############################################################################                   
# Run this to check what is going on in the moment                            #
###############################################################################
batch_attach() {
	screen -x ipfire
	if [ "$?" -eq "0" ]; then
		beautify message DONE
	else
		beautify message FAIL
	fi
}

###############################################################################                   
# This is the main batch function that runs one thing after an other          #
###############################################################################
batch_run() {	
	gettoolchain
	$0 build | tee $BATCHLOG
	[ $? -eq 0 ] && puttarget
	batch_mail
}

###############################################################################                   
# A function to send an email to the developers                               #
###############################################################################
batch_mail() {
	SUBJECT="IPFire.org ${HOSTNAME-$(hostname -f || hostname)} Build"
	MAILLOG=$BASEDIR/log_${MACHINE}/_mail.body.$$

	> $MAILLOG ## Empty the log

	## Form the message header
	echo -e "From: $MAIL_FROM\nTo: $MAIL_TO" >> $MAILLOG
	echo -e "Subject: $SUBJECT\n" >> $MAILLOG

	## Remove the colors when sending an email
	#  This has to be done better by anything else
	sed -e 's@.\[.;..m@@g' < $BATCHLOG >> $MAILLOG

	## Send the email
	python tools/sendEmail < $MAILLOG
	evaluate

	rm -f $MAILLOG
}
