#!/bin/bash

BUILD_DIR="${BASEDIR}/naoki_$$"
BUILD_ROOT="/buildroot.$$"
TOOLS_DIR=/tools_${MACHINE}

ARCH=i686

PACKAGES_TO_EXTRACT="coreutils filesystem perl util-linux-ng"

PACKAGES_PARALLELISM=2
PARALLELISMFLAGS=-j1

CFLAGS="-fomit-frame-pointer -pipe"
case "${ARCH}" in
	i?86)
		CFLAGS="-O2 -march=${ARCH} ${CFLAGS}"
		CXXFLAGS="${CFLAGS}"
		TARGET="${ARCH}-pc-linux-gnu"
		;;
esac

log INFO "Machine information:"
log INFO "    Hostname     : ${HOSTNAME}"
log INFO "    Architecture : ${MACHINE}"

log INFO "Target information:"
log INFO "    Architecture : ${ARCH}"
log INFO "    CFLAGS       : ${CFLAGS}"
log INFO "    CXXFLAGS     : ${CXXFLAGS}"
log INFO "    TARGET       : ${TARGET}"
log INFO "    Parallelism  : ${PARALLELISMFLAGS}"
