#!/bin/bash

BUILD_DIR="${BASEDIR}/build/naoki_$(date +"%d%m-%H%M").$$.${MACHINE}"
BUILD_ROOT="/buildroot.$$"
TOOLS_DIR=/tools_${MACHINE}
TOOLS_DIR_REAL=${BASEDIR}/build/tools_${MACHINE}

ARCH=i686

PACKAGES_MANDATORY="bash bzip2 coreutils cpio diffutils findutils gawk gcc grep"
PACKAGES_MANDATORY="${PACKAGES_MANDATORY} gzip make patch sed tar util-linux-ng"
PACKAGES_MANDATORY="${PACKAGES_MANDATORY} which"

PACKAGES_PARALLELISM=2
PARALLELISMFLAGS=-j5

CFLAGS="-fomit-frame-pointer -pipe"
case "${ARCH}" in
	i?86)
		CFLAGS="-O2 -march=${ARCH} ${CFLAGS}"
		CXXFLAGS="${CFLAGS}"
		TARGET="${ARCH}-pc-linux-gnu"
		;;
esac

log INFO "Machine information:"
log INFO "    Hostname     : ${HOSTNAME}"
log INFO "    Architecture : ${MACHINE}"

log INFO "Target information:"
log INFO "    Architecture : ${ARCH}"
log INFO "    CFLAGS       : ${CFLAGS}"
log INFO "    CXXFLAGS     : ${CXXFLAGS}"
log INFO "    TARGET       : ${TARGET}"
log INFO "    Parallelism  : ${PARALLELISMFLAGS}"
