#!/bin/bash

if [ -z "${BASEDIR}" ]; then
	echo "${0##*/}: ERROR: BASEDIR is not set." >&2
	exit 1
fi

export NAOKI_INCLUDE=1

. ${BASEDIR}/tools/common-include

. ${BASEDIR}/tools/naoki-constants
. ${BASEDIR}/tools/naoki-functions

log DEBUG "Started up naoki instance with pid $$"
