#!/bin/sh

. $(dirname ${0})/common-functions

gzip=gzip
if [ -x "/usr/bin/pigz" ]; then
	gzip=pigz
fi

case "${1}" in
	adjust)
		TARGET_PATH=${2}
		TOOLS_DIR="${TARGET_PATH}/tools_i686"

		#if [ -z "${TOOLS_DIR}" ]; then
		#	echo "$0: TOOLS_DIR not set." >&2
		#	exit 1
		#fi
		
		# If glibc is not compiled yet...
		if [ -e "${TARGET_PATH}/lib/libc.so.6" ]; then
			# Adjust linker
			mv -f ${TOOLS_DIR}/bin/ld{-new,}
			ln -sf ../../bin/ld \
				${TOOLS_DIR}/$(${TOOLS_DIR}/bin/gcc -dumpmachine)/bin/ld

			# Adjust spec file
			SPECS=$(dirname $(${TOOLS_DIR}/bin/gcc --print-libgcc-file-name))/specs
			rm -f ${SPECS}

			${TOOLS_DIR}/bin/gcc -dumpspecs | sed -e 's@/tools_i686@@g' \
			    -e '/\*startfile_prefix_spec:/{n;s@.*@/usr/lib/ @}' \
			    -e '/\*cpp:/{n;s@$@ -isystem /usr/include@}' > ${SPECS}
		fi

		for i in bin/bash bin/cat bin/echo bin/ln bin/mv bin/stty bin/pwd bin/rm bin/sh; do
			if [ -e "${TARGET_PATH}/${i}" ]; then
				continue
			fi
			mkdir -p $(dirname ${TARGET_PATH}/${i}) 2>/dev/null
			ln -sf ../$(basename ${TOOLS_DIR})/${i} ${TARGET_PATH}/${i}
		done

		for i in libgcc_s.so{,.1} libstdc++.so{,.6}; do
			if [ -e "${TARGET_PATH}/usr/lib/${i}" ]; then
				continue
			fi
			mkdir -p ${TARGET_PATH}/usr/lib 2>/dev/null
			ln -sf ../../$(basename ${TOOLS_DIR})/lib/${i} ${TARGET_PATH}/usr/lib/${i}
		done

		if ! [ -e "${TARGET_PATH}/lib/cpp" ]; then
			for path in /usr/bin/cpp $(basename ${TOOLS_DIR})/bin/cpp; do
				if [ -e "${TARGET_PATH}/${path}" ]; then
					ln -sf /${path} ${TARGET_PATH}/lib/cpp
					break
				fi
			done
		fi
		;;

	compress)
		TARGET=${2}
		COMPRESS_PATH=${3}

		target=$(mktemp)

		# Remove unneeded files
		rm -rf ${COMPRESS_PATH}/{info,man,share/{doc,info,locale,man}}
		rm -rf ${COMPRESS_PATH}/usr/src/*

		# Remove all static libs
		for i in $(find ${COMPRESS_PATH} -name "*.a"); do
			grep -q "_nonshared" <<<${i} && continue
			grep -q "libgcc" <<<${i} && continue
			rm -rf ${i}
		done
		rm -rf ${COMPRESS_PATH}/{lib/pkgconfig,libexec,var}

		for i in $(find ${COMPRESS_PATH} -name "*.la"); do
			rm -rf ${i}
		done

		# Strip all files
		for file in $(find_elf_files ${COMPRESS_PATH}); do
			strip --strip-debug ${file}
		done

		# Strip executeable files
		for file in $(find_elf_files ${COMPRESS_PATH}/bin ${COMPRESS_PATH}/*/bin); do
			strip --strip-all ${file}
		done

		cd ${COMPRESS_PATH} && tar --posix -c -p -S * | ${gzip} -9 > ${target}

		cat ${target} > ${TARGET}
		rm -f ${target}
		;;

	extract)
		ARCHIVE=${2}
		TARGET_PATH=${3}

		${gzip} -d < ${ARCHIVE} | tar x -C ${TARGET_PATH}
		;;

esac
