#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2010  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

umask 022
export PATH=/usr/sbin:/sbin:/usr/bin:/bin

exec &>/tmp/network.$(basename $0)

# Give the variables we get passed by pppd an own namespace
for i in IFNAME IPLOCAL IPREMOTE DNS1 DNS2 MACREMOTE; do
	export PPP_${i}=${!i}
	unset ${i}
done

. /lib/network/functions

# Zone equals IFNAME
ZONE=${PPP_IFNAME}

assert isset ZONE

if ! zone_exists ${ZONE}; then
	error "Zone '${ZONE}' does not exist."
	exit ${EXIT_ERROR}
fi

HOOK=$(zone_get_hook ${ZONE})

assert isset HOOK

if ! hook_zone_exists ${HOOK}; then
	error "Hook '${HOOK}' does not exist."
	exit ${EXIT_ERROR}
fi

hook_zone_exec ${HOOK} ppp-$(basename ${0}) ${ZONE}
