#!/bin/sh
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2007  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

umask 022
export PATH=/usr/sbin:/sbin:/usr/bin:/bin

. /lib/network/functions
. /lib/network/functions.ppp

for config in ${CONFIG_ZONES}/${DEVICE}/*; do
	if [ "$(ppp_linkname_get ${config})" = "${LINKNAME}" ]; then
		CONFIG=${config}
		. ${CONFIG}
		break
	fi
done

if [ -n "${HOOK}" ] && [ -x "${HOOKS_DIR}/${HOOK}.helper" ]; then
	exec ${HOOKS_DIR}/${HOOK}.helper --config=${CONFIG} \
		$(basename $0) $@
fi

exit ${EXIT_ERROR}
