#!/bin/sh

. /lib/network/hook-header

HOOK_NAME="ipv4-dhcp"
HOOK_TYPE="zone"

MESSAGE="DHCP Daemon..."
EXECUTEABLE="/sbin/dhclient"

case "${action}" in
	help)
		;;

	info)
		echo "HOOK_NAME=$HOOK_NAME"
		echo "HOOK_TYPE=$HOOK_TYPE"
		;;

	status)
		check_config zone
		pidfile="/var/run/dhclient_${zone}.pid"
		pidofproc -p ${pidfile} ${EXECUTEABLE} &>/dev/null
		exit $? 
		;;

	pre-up)
		;;

	post-up)
		check_config zone
		pidfile="/var/run/dhclient_${zone}.pid"
		if [ -e "${pidfile}" ]; then
			kill $(<${pidfile}) &>/dev/null
			sleep 1
		fi
		${EXECUTEABLE} -pf ${pidfile} ${zone}
		evaluate_retval start
		;;

	pre-down)
		check_config zone
		pidfile="/var/run/dhclient_${zone}.pid"
		killproc -p ${pidfile} ${EXECUTEABLE}
		evaluate_retval stop
		;;

	post-down)
		;;

	add)
		while [ $# -gt 0 ]; do
			case "$1" in
				--hostname=*)
					HOSTNAME=${1#--hostname=}
					;;
				*)
					echo "Unknown option: $1" >&2
					exit 1
					;;
			esac
			shift
		done
		cat <<EOF >${CONFIG_ZONES}/${zone}/ipv4-dhcp
HOOK="${HOOK_NAME}"
HOSTNAME="${HOSTNAME}"
EOF
		[ "$?" = "0" ] && exit ${EXIT_OK} || exit ${EXIT_ERROR}
		;;

	rem)
		;;
	
	*)
		echo "Usage: ${0} {config|pre-up|post-up|pre-down|post-down|status} [interface]"
		exit ${EXIT_ERROR}
	;;
esac

# End $NETWORK_DEVICES/services/ipv4-dhcp
