#!/bin/sh
########################################################################
# Begin $NETWORK_DEVICES/services/mtu
#
# Description : Sets MTU per interface
#
# Authors     : Nathan Coulson - nathan@linuxfromscratch.org
#               Jim Gifford - jim@linuxfromscratch.org
#
# Version     : 00.00
#
# Notes       : This sets the maximum amount of bytes that can be
#               transmitted within a packet. By default, this
#               value is set to 1500.
#
########################################################################

. /lib/lsb/init-functions
. /lib/network/functions

HOOK_NAME=mtu
HOOK_TYPE=zone

function check_config() {
	if [ -z "${MTU}" ]; then
		log_failure_msg "MTU variable missing from ${CONFIG}, cannot continue."
		exit 1
	fi
	if [ -z "${zone}" ]; then
		usage
		exit 1
	fi
}

function usage() {
	echo "Usage: ${0} {pre-up|post-up|pre-down|post-down|config} [interface]"
}

# First, parse the command line

while [ $# -gt 0 ]; do
	case "${1}" in
		--zone=*)
			zone=${1#--zone=}
			;;
		--config=*)
			. ${1#--config=}
			check_config
			;;
		-*)
			log_failure_msg "Unrecognized option: ${1}"
			exit ${EXIT_ERROR}
			;;
		*)
			action=${1}
			shift
			break
			;;
	esac
	shift
done

# Second, do the $action

case "${action}" in
	help)
		;;
	
	info)
		echo "HOOK_NAME=$HOOK_NAME"
		echo "HOOK_TYPE=$HOOK_TYPE"
		;;

	status)
		check_config
		mtu=$(cat /sys/class/net/${zone}/mtu 2>/dev/null)
		[ "$MTU" = "$mtu" ]
		exit $?
		;;

	pre-up)
		;;

	post-up)
		check_config
		message="Setting the MTU for ${zone} to ${MTU}..."
		echo "${MTU}" > "/sys/class/net/${zone}/mtu"
		evaluate_retval standard
		;;

	pre-down)
		check_config
		message="Resetting MTU for ${zone} to 1500..."
		echo "1500" > "/sys/class/net/${zone}/mtu"
		evaluate_retval standard
		;;

	post-down)
		;;

	config)
		MTU=$1
		check_config
		cat << EOF >> ${CONFIG_ZONES}/${zone}/${HOOK_NAME}
HOOK="${HOOK_NAME}"
MTU="${MTU}"
EOF
		exit $?
		;;

	*)
		usage
		exit 1
	;;
esac

# End $NETWORK_DEVICES/services/mtu
