#!/bin/bash
###############################################################################
#                                                                             #
# IPFire.org - A linux based firewall                                         #
# Copyright (C) 2009  Michael Tremer & Christian Schmidt                      #
#                                                                             #
# This program is free software: you can redistribute it and/or modify        #
# it under the terms of the GNU General Public License as published by        #
# the Free Software Foundation, either version 3 of the License, or           #
# (at your option) any later version.                                         #
#                                                                             #
# This program is distributed in the hope that it will be useful,             #
# but WITHOUT ANY WARRANTY; without even the implied warranty of              #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               #
# GNU General Public License for more details.                                #
#                                                                             #
# You should have received a copy of the GNU General Public License           #
# along with this program.  If not, see <http://www.gnu.org/licenses/>.       #
#                                                                             #
###############################################################################

DEBUG=
VERBOSE=

BOLD="\\033[1;39m"
NORMAL="\\033[0;39m"
ERROR="\\033[1;31m"

. /etc/init.d/networking/functions

function usage() {
	echo "Usage $0 - TODO"
	_exit $1
}

function debug() {
	if [ -n "$1" ]; then
		DEBUG=$1
		verbose $1
		return
	else
		if [ "$DEBUG" = "1" ]; then
			return 0
		else
			return 1
		fi
	fi
}

function verbose() {
	if [ -n "$1" ]; then
		VERBOSE=$1
		return
	else
		if [ "$VERBOSE" = "1" ]; then
			return 0
		else
			return 1
		fi
	fi
}

function decho() {
	debug && echo -e "${ERROR}$@${NORMAL}" >&2
}

function vecho() {
	verbose && echo -e "$@"  >&2
}

function error() {
	echo -e "${ERROR}ERROR${NORMAL}: $@" >&2
	_exit 1
}

function _exit() {
	decho "Exiting with code $1."
	exit $1
}

function port_show() {
	local port

	port=$(devicify $1)

	if ! device_exists ${port}; then
		error "Port ${BOLD}${port}${NORMAL} does not exist."
		return 1
	fi

	ip -s link show $port
}

function port_add() {
	local port
	local zone
	local hook
	
	zone=$1
	port=$(macify $2)
	hook=${3-ethernet}

	shift 3

	decho "Function: port_add"
	decho "  Zone: ${zone} Port: ${port} Hook: ${hook} $@"

	if ! zone_exists ${zone}; then
		error "Zone ${BOLD}${zone}${NORMAL} does not exist."
		return 1
	fi

	if [ -z "$port" ]; then
		error "Port ${BOLD}${port}${NORMAL} could not be found."
		return 1
	fi

	if ! device_exists ${port}; then
		error "Port ${BOLD}${port}${NORMAL} does not exist."
		return 1
	fi

	mkdir -p ${CONFIG_PORTS}/${port} 2>/dev/null
	if [ -x "/etc/init.d/networking/hooks/${hook}" ]; then
		ZONE=${zone} /etc/init.d/networking/hooks/${hook} ${port} add $@
		RET=$?
		if [ "$RET" -eq "0" ]; then
			vecho "Successfully added port ${BOLD}${port}${NORMAL} (${hook} $@) to ${BOLD}${zone}${NORMAL}."
			/etc/init.d/networking/port ${port} up
		else
			error "Hook ${BOLD}${hook}${NORMAL} exited with $RET."
			return $RET
		fi
	else
		error "Hook ${BOLD}${hook}${NORMAL} does not exist or is not executeable."
		return 1
	fi
}

function port_del() {
	local port
	local zone
	local hook

	zone=$1
	port=$(devicify $2)
	hook=${3-ethernet}

	shift 3

	decho "Function: port_del"
	decho "  Zone: ${zone} Port: ${port} Hook: ${hook}"

	if [ -x "/etc/init.d/networking/hooks/${hook}" ]; then
		/etc/init.d/networking/port ${port} down ## XXX How do we identify only that one hook?
		ZONE=${zone} /etc/init.d/networking/hooks/${hook} ${port} remove $@
		RET=$?
		if [ "$RET" -eq "0" ]; then
			vecho "Successfully removed port ${BOLD}${port}${NORMAL} (${hook} $@) from ${BOLD}${zone}${NORMAL}."
		else
			error "Hook ${BOLD}${hook}${NORMAL} exited with $RET."
			return $RET
		fi
	else
		error "Hook ${BOLD}${hook}${NORMAL} does not exist or is not executeable."
		return 1
	fi
}

function zone_show() {
	local zone
	zone=$1

	if [ -z "$zone" ]; then
		for zone in ${CONFIG_ZONES}/*; do
			zone_show $(basename $zone)
		done
		return
	fi

	if ! zone_exists ${zone}; then
		error "Zone ${BOLD}${zone}${NORMAL} does not exist."
		return 2
	fi

	echo    "##################################################"
	echo -e "# ${ERROR}ZONE INFO - ${zone}${NORMAL}"
	echo    "##################################################"

	# Up or down?
	if device_exists ${zone}; then
		echo -e "# Device is ${ERROR}up${NORMAL}."
	else
		echo -e "# Device is ${ERROR}down${NORMAL}."
	fi
	echo "#"

	# Ports
	echo -e "# ${ERROR}Ports:${NORMAL}"
	local port
	for port in ${CONFIG_ZONES}/${zone}/port-*; do
		port=${port##*/}
		echo "#  ${port#port-}"
		debug && echo "#  TODO: Is port up or down?"
	done
	echo "#"

}

function zone_add() {
	local zone

	zone=$1
	if zone_exists ${zone}; then
		error "Zone ${BOLD}${zone}${NORMAL} already exists."
		return 2
	fi

	mkdir -p ${CONFIG_ZONES}/${zone}
	vecho "Successfully added zone ${zone}."
}

function zone_del() {
	local zone

	zone=$1
	if ! zone_exists ${zone}; then
		error "Zone ${BOLD}${zone}${NORMAL} does not exist."
		return 1
	fi

	rm -rf ${CONFIG_ZONES}/${zone}
	vecho "Successfully removed zone ${zone}."
}

while [ "$#" -gt 0 ]; do
	arg=$1
	shift
	case "$arg" in
		--debug|-d)
			debug 1
			decho "Debug mode is enabled."
			;;
		--verbose|-v)
			verbose 1
			vecho "${BOLD}Verbose mode is enabled.${NORMAL}"
			;;
		help|-h|--help)
			usage 0
			;;
		start|stop|restart|reload)
			exec /etc/init.d/network $arg
			;;
		port|po|p)
			arg=$1
			shift
			case "$arg" in
				show)
					port_show $@
					_exit $?
					;;
			esac
			;;
		zone|zo|z)
			arg=$1
			shift
			case "$arg" in
				add)
					zone_add $@
					_exit $?
					;;
				del)
					zone_del $@
					_exit $?
					;;
				show)
					zone_show $@
					_exit $?
					;;
				addport)
					port_add $@
					_exit $?
					;;
				delport)
					port_del $@
					_exit $?
					;;
			esac
			;;
		*)
			usage
			;;
	esac
done
